### ISSUE TITLE
Ch 19 intro/preface

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#101]
The last of the three sentences just seems awkward to me.  Why does open get special attention, when close is important, too?  Perhaps you can combine the last two sentences to whet the appetite of the reader while not singling out one built-in function:

"Python makes these operations easy with its built-in functions such as open and close."

**Comment by mattharrison** [comment]
How is this:


Reading and writing files is common in programming. Python makes these operations
easy. We can read the both text and binary files. We also have a choice of reading
a file by number of bytes, lines, or even the whole file at once. There are similar
options available for writing files.

**Comment by Rad-Prof** [comment]
Much better!
