### ISSUE TITLE
19.1 truncate a file

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#102]
I hadn't heard the word "truncate" with files before in the way I thought you were meaning so I googled it.  I thought with you used an existing filename, the file was overwritten.  I think what you are saying is that the file is truncated to one of 0 length.  In the googled definitions truncate seems to be usually associated with a a length (same is true for truncating decimals in mathematics, you have to specify the decimal place).

So my suggestion is to replace "truncate it..." with "overwrite it (truncating to 0 length)..."

**Comment by Rad-Prof** [comment]
You say something like this later in section 19.5.  Whatever terminology you use, consider the table in 19.1 that also says "truncate."

**Comment by mattharrison** [comment]
Changed Truncate to Aug 22
