### ISSUE TITLE
9. Strings: with_quote example

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#105]
>\>\>\> with_quote = "I ain't gonna"
>
>As illustrated in the with_quote example you can put double quotes inside of a single quoted string—and vice versa.

While the "vice versa" does apply to your example, given that you first call the reader's attention to "double quotes inside of a single quoted string", I think you should either change the example or the first clause of your sentence so that they match each other. I also added a comma after "example".

Like this:

**>>> with_quote = "I ain't gonna"**

**As illustrated in the with_quote example, you can put single quotes inside of a double quoted string—and vice versa.**

-or-

**\>\>\> with_quote = 'he said, "not gonna do it"'**

**As illustrated in the with_quote example, you can put double quotes inside of a single quoted string—and vice versa.**

**Comment by mattharrison** [comment]
Fixed Aug 22. Thanks
