### ISSUE TITLE
20.1 one-to-one

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#107]
Top of page 150 in 8/15 version:  "one-to-one" is used as an adjective modifying "mapping" and therefore should be hyphenated.

**Comment by Rad-Prof** [comment]
Also in the next sentence, I think it should be "many more" versus your "much more"

**Comment by Rad-Prof** [comment]
In the same page and in the last sentence just before the first Tip of the chapter, I think it would read better to replace "encoding as many" with "encoding, since many"

**Comment by mattharrison** [comment]
Thank you. Aug 22
