### ISSUE TITLE
20.2

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#108]
I'm loving the new terminology I'm learning, but in this section I'm not sure I'm parsing the definition correctly for tofu.

If it is called tofu because it looks like an empty box, and the diamond with a question mark has no corresponding name, the I think you should write "_tofu_, **because** it looks like an empty box, or a diamond with a question mark."

If both symbols described are identified as tofu, then I'd write "_tofu_, **because** it looks **either** like an empty box or a diamond with a question mark."

Bold was added to show the words I added.  Also note the change in comma around "or" in this suggested edit.

**Comment by Rad-Prof** [comment]
Also, you didn't include the output of "print(result, result2, result3)" even though you talked about it.  Omitting it made me try it, but your convention seems to be to provide the output, especially if you write about it.

**Comment by mattharrison** [comment]
Thanks for the feedback. Glad that your are learning new words :)

Aug 22
