### ISSUE TITLE
Chapter 9 (Grammar, etc.)

### ISSUE THREAD

**Issue by wynand1004** [mattharrison/IllustratedPy3#11]
attributes can be looked
up used .attribute_name syntax -> attributes can be looked
up **using** .attribute_name syntax

Prefix integers. Ob -binary, 0o -octal, 0x -hex - For some reason, the zeros appeared different my computer and had dots in the middle for octal and hex.

http -> https for pyformat.info

.for-mat -> .format

a left justified area of 10 character -> a left justified area of 10 character**s**

**Comment by mattharrison** [comment]
Thanks.
