### ISSUE TITLE
20.3 Encoding versus decoding

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#110]
Your explanation is good. 

Another way of looking at encoding and decoding is that encoding transforms a readable or meaningful representation into an abstract representation (Unicode to bytes or letter to bytes), and decoding transforms abstract representations to a readable or meaningful representations.

**Comment by mattharrison** [comment]
I've added this but tweaked it slightly. Perhaps need some more work:

Perhaps one of the keys to grokking Unicode in Python is to understand that you
*encode a Unicode string to a byte string*. You never encode a byte string. You
*decode a byte string to a Unicode string*. Likewise, you never decode a Unicode
string. Another way of looking at encoding and decoding is that encoding
transforms a human-readable or meaningful representation into an abstract
representation meant for storage (Unicode to bytes or letter to bytes), and
decoding transforms that abstract representation back to a human readable or meaningful
representation.

**Comment by Rad-Prof** [comment]
Much better!
