### ISSUE TITLE
Ch 21:  Object-oriented before a noun should be hyphenated

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#117]
https://english.stackexchange.com/questions/150055/object-oriented-vs-object-oriented

**Comment by mattharrison** [comment]
BTW, will you email me directly? I would love to list you as an editor on the book due to your tremendous help. (I can't tell who you are from the gh handle)

**Comment by Rad-Prof** [comment]
Will do, and thank you so much.  That would be wonderful.

**Comment by mattharrison** [comment]
Thanks for the email! Fixed in Aug 22
