### ISSUE TITLE
3.1 Interactive Interpreter

### ISSUE THREAD

**Issue by gm3dmo** [mattharrison/IllustratedPy3#12]
The REPL and IDLE are being introduced in this small section:

Other environments,
such as IDLE, also embed an interactive interpreter.
Another option is to start IDLE, the editor included with Python,
by typing python3 -m idlelib.idle.

Other environments such ad IDLE and Another otpion is to start IDLE

I find this confusing.

It took me a while to find IDLE on my Mac (never used it on Mac).

![image](https://user-images.githubusercontent.com/4660778/29248602-0b472cb8-8014-11e7-96f0-1e59a589fd9b.png)

Might need a little more detail there.

**Comment by gm3dmo** [comment]
I've seen self taught people do amazing things with the IDLE and thought "I wish I could used the IDLE like that".

**Comment by jaypsingh** [comment]
**Section 3.1** says "Another option is to start IDLE, the editor included with Python,
by typing **python3 -m idlelib.idle**."
I tried this command on my **windows** machine and couldn't make it work from home as well as from python3 install dir.
<img width="353" alt="idle" src="https://user-images.githubusercontent.com/15726294/29250153-62447132-800b-11e7-9600-72779ddb700b.PNG">
<img width="392" alt="idle2" src="https://user-images.githubusercontent.com/15726294/29250152-62443032-800b-11e7-9f93-cf353a9b6734.PNG">

**Feedback:**
1. Please include in the description if this command will work on windows .
2. Please include in the description where to type this command, on command prompt home or by browsing to directory where python is installed ?

**Comment by jaypsingh** [comment]
This is related hence not opening a new defect.
**Section 3.2** says If you typed python3 from the commandline, or launched IDLE, you will see >>>. Type 2 + 2 like shown below and hit enter:

**Suggestion**
"Type 2 + 2 like shown below and hit enter" can come on next line to make it look neat. 
It will be great to have the 2+2 included in the screenshot you have added. Something like below:
<img width="505" alt="idle3" src="https://user-images.githubusercontent.com/15726294/29250252-329eab1c-800d-11e7-9a06-fa4188b1e975.PNG">

**Comment by Rad-Prof** [comment]
Also same section so continuing this string of comments on the REPL.  Please include the command "quit()" so new users know how to exit the REPL.

**Comment by mattharrison** [comment]
@jaypsingh What platform are you on? Did you install from python.org? You have a typo ``idlelib.lib`` should be ``idlelib.idle``

@gm3dmo Can you please elaborate on what you found confusing. The terminal? The command? The wording? Thanks

**Comment by jaypsingh** [comment]
@mattharrison I am so sorry for the typo. I am on windows and i had installed python from python.org.
Yes **python -m idlelib.idle worked** for me. My apologies.
Please note that when i type "python3 -m idlelib.idle" i get an error 
'python3' is not recognized as an internal or external command, operable program or batch file.

**Comment by mclaughlin** [comment]
The first sentence in 3.1 is an incomplete sentence:

**Because Python has an interpreter, which enables what is known as an interactive interpreter or REPL (Read Evaluate Print Loop).**

Possible alternatives:

Because Python has an interpreter, it enables what is known as an interactive interpreter or REPL (Read Evaluate Print Loop).

-or-

Python's interpreter enables what is known as an interactive interpreter or REPL (Read Evaluate Print Loop).

**Comment by mclaughlin** [comment]
I also found the fact that 3.1 is titled "Interactive Interpreter" and 3.2 "A REPL Example" to possibly be confusing to someone new to these terms. Given that both terms are being used synonymously in 3.1, it might prevent confusion to title 3.1 "Interactive interpreter / REPL" or maybe simply "REPL". And then keep 3.2 "A REPL Example".

**Comment by mattharrison** [comment]
Aug 29
