### ISSUE TITLE
21.3 repetitive use of "think"

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#121]
Second sentence of the section might be better as:

"One way to think of the Chair class is as a factory."

I'm not sure about the next sentence about the reference to "bare objects."  Is it correct to say: "The factory takes in references to instances of Chair and churns out chair objects."  Even if that isn't correct I think it it reads better if "in" is after "takes," and you don't need the comma because there aren't two sentences that are being joined, only two verb clauses.

**Comment by Rad-Prof** [comment]
Never mind my comment on "bare objects"  since you explain it in the next paragraph.  I should have kept reading...

**Comment by mattharrison** [comment]
Thanks Aug 22
