### ISSUE TITLE
17 Preface suggestion

### ISSUE THREAD

**Issue by kaumaron** [mattharrison/IllustratedPy3#129]
In the section where you introduce functions the following reasoning is given: 

> If we have code that we repeatedly run in our program, rather than just copying and pasting it, we can put it in a function once, then call that function multiple times. This gives us less code to reason about, making our programs easier to understand

I would like to suggest adding in that it also makes tweaking the code later easier as it's only in one location.

**Comment by mattharrison** [comment]
Great suggestion Aug 22 fix
