### ISSUE TITLE
2.1 Python Installation

### ISSUE THREAD

**Issue by gm3dmo** [mattharrison/IllustratedPy3#13]
Although the instructions here are clear and a nice link is provided as a footnote to the python.org download site. A lot of people's experience of the web is typing the thing they are doing into google.

They are might well end up installing the ActiveState version of Python:

![image](https://user-images.githubusercontent.com/4660778/29248550-b1665b02-8012-11e7-9107-ae44195845fa.png)

A note on that might be useful?

**Comment by Rad-Prof** [comment]
Also I'm wondering if it is worth mentioning to beginning users that the interactive python REPL also shows what version is installed such as:
iMac:Documents user$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
or:MacBook-Pro-3:~ Roger$ python
Python 3.5.2 |Anaconda 4.1.1 (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by mattharrison** [comment]
@gm3dmo Active Python is a perfectly fine Python distro. If they installed that, they should be fine. (Used it for a while myself quite a few years ago when I was forced to use Windows)

@Rad-Prof  Added a note in Aug14
