### ISSUE TITLE
19.1 (Page 141) Open File Syntax

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#130]
In below lines. We talk about python open command return type followed by the parameters passed.
![image](https://user-images.githubusercontent.com/15726294/29737821-370da8ee-89e3-11e7-9f90-fe49ead4d684.png)

This is great, but for a visual person like me it would help to include the syntax and then talk about the return type and parameters passed. Something like below:
The Python function, open, returns a file object. 
**Syntax** 
_file_object = open(file_name [, access_mode])_
The first parameter, the filename is required. 
The second parameter the mode, which determines if you are reading or writing a file, and
if it is a text or binary file.

**Comment by mattharrison** [comment]
Great. Fixed Aug 22
