### ISSUE TITLE
19.1 (page 141) Example of Open reword seuggestion

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#131]
In below example since the path is valid for a unix machine but for a windows user this example may not work. 
![image](https://user-images.githubusercontent.com/15726294/29737877-64a3459c-89e4-11e7-907a-0c2e77c45697.png)

Can i recommend to reword it something as below.
Here is an example to open a file a.txt located in **path*** '/tmp' for writing.
Python will create that file, or truncate it if it already exists:
 _a_file = open('/tmp/a.txt', 'w')_ 

***path**: Please replace the path (/tmp) with a valid path in your system based on OS you are working with.

**Comment by mattharrison** [comment]
Added a note in Aug 22
