### ISSUE TITLE
Section 19.4 Sentence can be reworded to avoid use of that twice 

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#133]
In section 19.4 below sentence:
![image](https://user-images.githubusercontent.com/15726294/29738040-6dbf533e-89e7-11e7-8b7f-d2de262dc537.png)

Do you think it will sound better with below reword:
How does **it** work that you can iterate directly over the file object instance?

**Comment by mattharrison** [comment]
Changed Aug 22? How can you iterate directly over the file instance?
