### ISSUE TITLE
Section 19.5 File Write might also return exception

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#134]
In Section 19.5 you mention below 
![image](https://user-images.githubusercontent.com/15726294/29738070-14ae1130-89e8-11e7-9353-99d8038aa38d.png)

which is true. But i think its worth mention that for certain cases like invalid path etc the method will throw exception.
The above method will overwrite the file _/tmp/names.txt_ if it exists, otherwise the file will be created.
If other cases if the file can't be created or written due to access violation, write protection or path is invalid the method will through exception.

**Comment by mattharrison** [comment]
Thanks!

Aug 22 update


The above method will try overwrite the file ``/tmp/names.txt`` if it
exists, otherwise the file will be created. If you don't have permission
to access the file a ``Permission Error`` will be thrown. If the
path is bad you will see a ``FileNotFoundError``.
