### ISSUE TITLE
Section 19.5 Additional Notes.

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#135]
This is just a suggestion (please ignore if not helpful)
Do you think it will be worth adding an additional note mentioning that on windows the file path should be raw string like r"c:\Lab".

I see on my interpreter if I don't pass raw string i get OSError exception. But same path works great if i convert the path to a raw string.
![image](https://user-images.githubusercontent.com/15726294/29738161-4013df38-89ea-11e7-802f-d95ae992e8b1.png)

**Comment by mattharrison** [comment]
Aug 22 fixed
