### ISSUE TITLE
19.6 (Page 146) Closing a file

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#136]
In section 19.6 (page 146) Closing a file section after citing few reasons why weshould explicitly close your
files you also mention
![image](https://user-images.githubusercontent.com/15726294/29738208-36cecc52-89eb-11e7-93ec-6884f58daca8.png)

I am not sure which case you meant to mention here. Do you think that this requires re-wording.

**Comment by mattharrison** [comment]
Updated Aug 22. Thanks for the feedback
