### ISSUE TITLE
19.9 Exercise (Page 148) suggesting reword.

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#137]
For Exercise 1 in this chapter, i think it can be reworded to make the problem statement more clear for some readers. I felt the the first line a bit confusing:
![image](https://user-images.githubusercontent.com/15726294/29741831-4b6a6c6e-8a42-11e7-8842-18a4eb11fe6f.png)

Please see if you like the below reword:
Create a function to create a comma separated value (CSV) file 
from list of tuples as input to the function. 
Tuples will consists of name, address and age. 

Top header row should be "name","address","age"
Followed by the entries in each tuple.

An example output is as below:
Name,Address,Age
George,4312 Abbey Road,22

**Comment by mattharrison** [comment]
Fixed Aug 22
