### ISSUE TITLE
19.9 Exercise 2 (Page 148) suggesting reword. 

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#138]
For Exercise 2, should it be worded as key instead of key names.
![image](https://user-images.githubusercontent.com/15726294/29741885-4fda2b26-8a43-11e7-9d3f-f5af6800f629.png)

Also do you want to add a hint (like below), since i have seen some times if a user can't resolve a problem they just skip it. If you feel its un-necessary than please ignore. 
Hint: A dictionary key can have multiple values for a key in tuple (or list or other data structure) like below
{'name':('George','Matt','Dave')}

**Comment by mattharrison** [comment]
Updated Aug 22
