### ISSUE TITLE
Section 17.4 Default Parameters (Page 131) Formatting Error

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#140]
On page 131 in the Tip section there is a formatting error. 
"Because"  is followed by a line in next page "of the way Python works...." which is not in the Tip box. 
Please consider re-formatting. 
![image](https://user-images.githubusercontent.com/15726294/29742765-b6287df6-8a52-11e7-8479-913be59a4af7.png)

**Comment by mattharrison** [comment]
Aug 22
