### ISSUE TITLE
Section 17.7 Exercise 1 and 2 suggesting reword

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#141]
**(same suggestion applies to question 2 also)**

For exercise question 1 in section 17.7:
![image](https://user-images.githubusercontent.com/15726294/29742852-9eb78a16-8a54-11e7-8849-8da9f6e78d51.png)

I suggest to reword like below just for the adding clarity in the problem statement, if that makes sense to you too.
Write a function, _is_odd_, that takes an integer as input and returns a boolean as output, stating whether **the given number** is an odd number. Function returns 
_True_ if the number is _Odd_
_False_ if the number is _not odd_

**Comment by mattharrison** [comment]
Aug 22
