### ISSUE TITLE
Section 17.7 Exercise 3 suggesting reword

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#142]
Just for shake of consistency it would be awesome if the question 3 is also written in same pattern as question 1 and 2.
I mean question 1 and 2 (and 3 too) writes "takes an integer... returns a boolean..."
Question 3 writes "should take a ... and return ..."

Can i suggest the below reword :
Write a binary search function. The function **takes a sorted sequence as input and returns the index of the item it is searching for as output**.
Function should return -1 if the item is not found.

**Comment by mattharrison** [comment]
Aug 22
