### ISSUE TITLE
Section 17.7 Exercise 3 Improved problem statement

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#143]
I am resubmitting this as a different issue since i didn't want to add confusion to the suggestion here with my other issue submitted on the same problem. I hope you don't mind for that.

This issue is more on the problem statement than just reword.

The problem statement says:
![image](https://user-images.githubusercontent.com/15726294/29743005-f04e1af0-8a56-11e7-9f0f-d739666c764f.png)

But i guess, we should also pass the "item" that have to be searched in the sorted sequence. 
Hence i will suggest below update in the problem statement.
Write a binary search function. The function takes a _sorted sequence_, and _item_ as input and returns the index of the _item_ (in the sequence) as output.
Function returns -1 if the item is not found.

**Comment by mattharrison** [comment]
Aug 22
