### ISSUE TITLE
Section 17.7 Exercise 4. Suggesting Reword.

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#144]
Section 17.7, Exercise 4 is great. Loved it. 
Can i suggest below change, just to add some clarity to second line of the problem statement . My changes are updated in Bold to the original exercise. My suggestion is mainly around the second line or the exercise. 

_Suggested Change:_
Write a function that takes camel cased **strings as input** (ie ThisIsCamel-Cased), and converts them to snake case (ie this_is_camel_cased).
Modify the function **by adding an additional argument as** optional separator **to* convert the given input string** to kebab case (ie this-is-camel-case).

**Comment by mattharrison** [comment]
Aug 22
