### ISSUE TITLE
Chapter 21 Classes Introduction. Suggesting italicize the keyword

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#145]
In chapter 21 introduction you mention this:
![image](https://user-images.githubusercontent.com/15726294/29746528-f26636c0-8aaa-11e7-8f1e-d8e4046a10c0.png)

I suggest to italicize the keyword to distinguish it form normal text. Also should it be 'is' or 'are', not quiet sure of the sentence structure. I have given my suggested change below.

_Suggested Change:_
There are some exceptions, keywords such as _in_ **is** not an object.

**Comment by mattharrison** [comment]
Aug 22
