### ISSUE TITLE
Section 21.1 (Page 162) Unclear Sentence.

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#146]
in section 21.1 Planning for a class, page 162 you mention "For other people that matter."
![image](https://user-images.githubusercontent.com/15726294/29746592-4c9bdc1a-8aad-11e7-824f-9142815e4b2c.png)

I guess you meant "For other people that might matter."

**Comment by mattharrison** [comment]
Aug 22
