### ISSUE TITLE
Section 21.2 Defining a class. Very minor feedback

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#148]
May be this is intentional, and if so i am sorry, please ignore my comments here.
 
Just wanted to bring the below sentence to your attention
![image](https://user-images.githubusercontent.com/15726294/29746631-fb7ef554-8aae-11e7-91ab-7c5ada40e692.png)

Did you mean  "We just need to give it **a name**" instead of "our name" ?

**Comment by mattharrison** [comment]
Aug 22
