### ISSUE TITLE
Section 21.2 Defining a class. Notes Have a break of one page

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#149]
In Section 21.2 Defining a classs, Notes on page 164 continues on page 166. There is a "Custom Class" diagram on page 165. 
The diagram is helpful but Please consider to put the diagram before or after the Notes. Reader may loose the context with the break of a page. 
![image](https://user-images.githubusercontent.com/15726294/29746716-2a72e850-8ab1-11e7-8b5d-54ff77b7a214.png)

**Comment by mattharrison** [comment]
Aug 22
