### ISSUE TITLE
Section 21.2 (Page 165) Custom Classes Diagram Requesting Reword

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#150]
I felt the below highlighted Sentence in in the custom class diagram a bit confusing.
It would be awesome if you can please reword this sentence for clarity of readers like me.

![image](https://user-images.githubusercontent.com/15726294/29746747-43c2ca86-8ab2-11e7-8ada-e22c3f426134.png)

**Comment by mattharrison** [comment]
Aug 22
