### ISSUE TITLE
Section 21.9 Exercise 1 Silly suggestion but...

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#152]
For Exercise question 1 of section 21.9 you use 'she' for a user. I don't know if that intentional. 
![image](https://user-images.githubusercontent.com/15726294/29746878-719d5238-8ab6-11e7-84bd-1a254c0e5df4.png)

Not at all important but, can i suggest to use 'user' or 'he or she' instead. (only if you would agree)

_Suggested Change:_
Imagine you are designing a banking application. 
What would **a user** look like? 
What attributes **the user** would have? 
What methods "the user" would have ?

**Comment by mattharrison** [comment]
Gonna leave it. Like that it caught you off guard Aug 22
