### ISSUE TITLE
Section 21.9 Exercise 3. A Note about 'Tweet'

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#153]
For Exercise question 3 of section 21.9 
![image](https://user-images.githubusercontent.com/15726294/29746906-5ba6256c-8ab7-11e7-87b5-aaf3a1b3bba3.png)

The question itself is great and perfect. 
But i am pretty sure that many people around the world does not use tweeter or understand what are the attributes of tweet 
I myself was introduced to tweeter only a few weeks back. :)

Hence can i suggest to add a note about 'tweet' like below.

_Suggested Update:_
Create a class that could represent a tweet*.

*tweet: Tweets are like text messages. Only difference is that along with text message you can also share multimedia file and tag people. Tweets are also publicly visible by default, but senders can restrict message delivery to just their followers.

**Comment by mattharrison** [comment]
Aug 22
