### ISSUE TITLE
Chapter 22 Introduction (Page 175) Inheritence

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#154]
In the introduction of chapter 22 you say this:
![image](https://user-images.githubusercontent.com/15726294/29752387-eae4710c-8b2a-11e7-8bda-112b8e279d5d.png)

I was wondering if it will be helpful to reader to say "This process is called _Inheritance_ " after the highlighted line.

**Comment by mattharrison** [comment]
The next paragraph introduces inheritance. Aug 22
