### ISSUE TITLE
Section 28.9 Exception is Blank

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#155]
In Appendix you have Section 28.9 which i blank.
I assume you intend to add something here but have not added yet (at least in the 22 Aug version of the book).
In case you don't add anything in this section, it would be advisable to remove this. 
![image](https://user-images.githubusercontent.com/15726294/29757343-30c40bd0-8b79-11e7-9c04-ce481b92c92f.png)

**Comment by mattharrison** [comment]
Removed Aug 29
