### ISSUE TITLE
Chapter 26 Introduction (Page 209) Suggesting a improved docstring

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#156]
Chapter 26 is great resource. :) . But i am still giving this feedback just a reviewer. I hope it helps. 

The introduction says this
![image](https://user-images.githubusercontent.com/15726294/29757638-4dcdc4d0-8b7b-11e7-8695-7e81ad8c621e.png)

In the highlighted section we say _It includes the source for a simplified implementation of the Unix command cat._
Some reader might not be from unix/linux background and may not really understand the purpose of this program (or what is _cat_ command) from the introduction (or docstring). I think it would be of real help to add the docstring to the program that explains what does this program really do do.  That will also help you to prove your point of the importance of detailed and clear docstring.

**Comment by mattharrison** [comment]
Great idea Aug 22
