### ISSUE TITLE
Chapter 26 Introduction (Page 209) Suggesting Reword

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#157]
The introduction section of Chapter 26 (Page 209) says this (please see highlighted text)
![image](https://user-images.githubusercontent.com/15726294/29757792-86231d52-8b7c-11e7-925d-85024a8b8311.png)

in the highlighted text you say "This will illustrate **where code is located** in a typical Python script."
I really apologize for my ignorance but i assume that you meant "This will illustrate **how the code is layout** in a typical Python script."

**Comment by mattharrison** [comment]
Aug 22
