### ISSUE TITLE
9.3 Stings Note

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#161]
>The .format method on a string replaces the % operator which was similar to C’s printf. This operator is still available and some users prefer it because it requires less typing for simple statements and because it is similar to C. %s, %d, and %x are replaced by their string, integer, and hex value respectively.

Are you making a distinction between the available operators in Python 2 and 3? And if so, maybe it would be good to structure the paragraph like this:

**In Python 3,** the .format method on a string replaces the % operator **from Python 2,** which was similar to C’s printf. **The % operator** is still available and some users prefer it **as** it requires less typing for simple statements and because it is similar to C. %s, %d, and %x are replaced by their string, integer, and hex value**s** respectively.

**Comment by mattharrison** [comment]
Thanks! Aug 22
