### ISSUE TITLE
23.2 explanation of except block

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#166]
At the top of page 185, it reads as if ANY error thrown in the try block will execute the except block.  I am learning here, so bear with me, but I thought the except block was only executed if the exception matched that noted in the code.  If so, then I'd suggest replacing "an" with "the stated" or "the given"; if not then I will just keep reading and learning.

**Comment by mattharrison** [comment]
You are correct. Updated accordingly Aug 22
