### ISSUE TITLE
23.6 missing word describing INI files

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#169]
"These files are usually used _for_ configuration and..."

I'm not sure for is the missing word, but something's missing.

**Comment by Rad-Prof** [comment]
Just after that the next sentence has some article issues.  I think you meant:  "This method tries to read **a** configuration from **a** dictionary."

**Comment by Rad-Prof** [comment]
In the next to last sentence you grammatically need a semicolon in front of "the last one wins" instead of a comma, or you need a conjunction such as "and" after the comma.

**Comment by mattharrison** [comment]
Aug 22
