### ISSUE TITLE
6.3 - "Cattle tags" defined twice

### ISSUE THREAD

**Issue by wdennis** [mattharrison/IllustratedPy3#17]
(Using 8/11 version of book)

Pg 25 - para beginning "One way to keep track of cattle is to use cattle tags" defines cattle tags.
Then, two para's later, "Cow tags (for those who have not ventured out to the country) are usually..." is another definition.

Consider consolidating definitions, don't need two.

**Comment by mattharrison** [comment]
Fixed in Aug14
