### ISSUE TITLE
Misleading wording on superclass. 

### ISSUE THREAD

**Issue by bjones-sigma** [mattharrison/IllustratedPy3#176]
You have chosen a great example to illustrate -- your choice of examples for class hierarchy are really clean and illustrative -- but the wording of this caption was really difficult.  I had to read it a dozen times to figure out what you were seeing. 

_Figure 22.1: A figure illustrating that a subclass points to its parents class
with the __bases__ attribute. The lookup mechanism for attributes on an
instance starts with looking at the instance, then the class if that fails, and
finally the base classes if that fails._

(a.) It's a caption so "a figure illustrating" is unnecessary and throws you off. 
(b.) You are looking for a noun -- a rule list.  Describe it as such. 

This wording is mine, but it is nominative and sparser.
"Search order for attributes and methods of a subclass.  If the instance defines the name, that is used.  After the instance, the class is searched.  Failing that, base classes of the class are searched.

**Comment by mattharrison** [comment]
My update. Let me know if this is more clear

  Illustration of the ``__bases__`` attribute in a subclass. This connection
  between a subclass and its parent classes allows us to look up attributes in a
  well defined manner. If the instance has the attribute defined, that is used.
  After the instance, the class (``__class__``) of the instance is searched.
  Failing that, parent classes (``__bases__``) of the class are searched.

**Comment by mattharrison** [comment]
Aug 29
