### ISSUE TITLE
General comment on choice of words

### ISSUE THREAD

**Issue by vahtras** [mattharrison/IllustratedPy3#177]
As a reader I am a bit oversensitive to  words like  'just' and 'simply' in teaching material. These words seldom contribute to a good learning experience, as a teacher these are words that easily slip out, while they often make the learner feel stupid if they don't get it at once. I recommend that you review the places where these words are used and keep them only where you think it is  motivated. A pythonic examination:

    >>> import collections
    >>> c = collections.Counter(open('beg3-aug22.txt').read().split())
    >>> c['simply']
    29
    >>> c['just']
    59

Regards,
Olav

**Comment by mattharrison** [comment]
Great comment. How's this:

    >>> import collections
    >>> c = collections.Counter(open('template/begpy3.rst').read().split())
    >>> c['simply']
    1
    >>> c['just']
    11
