### ISSUE TITLE
Chapter 2 - minor typos

### ISSUE THREAD

**Issue by jamesscottbrown** [mattharrison/IllustratedPy3#178]
There are some minor issues with Chapter 2.

p.5 "Download the file, ~~and~~ open it by double clicking it, and follow the instructions to finish the installation."

p.6 "Likewise, Mac users should download the ~~m~~*M*ac"

p.6 "most Python installations include IDLE ~~. IDLE~~ *, which* has decent Python editing features."

p.7 "Popular editors with decent Python support include Emacs, Vim, Atom, Visual Studio Code, and ~~Sublimetext~~ *Sublime Text*. "

**Comment by mattharrison** [comment]
Thanks Aug 29
