### ISSUE TITLE
2.4 Exercise 2

### ISSUE THREAD

**Issue by jamesscottbrown** [mattharrison/IllustratedPy3#179]
It's unclear what is meant by "Support python" in the first question of exercise 2 of section 2.4.

This first question seems redundant with the subsequent 3, so I would change the questions to 

* Do syntax highlighting *of Python code*?
* Run *Python code* in a REPL for you?
* Provide a debugger for stepping through *Python* code?

**Comment by mattharrison** [comment]
Great suggestions. Aug 29
