### ISSUE TITLE
Typos/improvements to text in Chapter 3

### ISSUE THREAD

**Issue by jamesscottbrown** [mattharrison/IllustratedPy3#180]
p. 10 "Python has an intepreter, which is also known as an *interactive interpreter* or *REPL* (Read Evaluate Print Loop)"

This suggests that "interpreter" and "interactive interpreter" have the same meaning, so I would instead say simply that "Python has an *interactive interpreter*  or *REPL* (Read Evaluate Print Loop)"

p.10 "This is a loop that waits ~~for input~~ *until there is input to read in*, *then* evaluates it (interprets it), and prints out ~~results~~ *the result*"

It is good to use each word of the acronym in the explanation

p. 11 
"it will print out the version of Python, some information about the build, and ~~give you~~ some hints to type."
or
"it will print out the version of Python, some information about the build, and ~~give you some hints to type~~ *some suggested commands for you to type*."

p. 12  "Below is an example to illustrate where the read, evaluate, print, and loop come from"

This could be re-phrased as something like  "Below is an example to show why the Read, Evaluate, Print Loop was given this name". Alternatively, this could simply be "Below is an example of how the REPL can be used", as the term was previously explained.

**Comment by mattharrison** [comment]
Awesome. Thanks Aug 29
