### ISSUE TITLE
Typos/improvements to text in Chapter 4

### ISSUE THREAD

**Issue by jamesscottbrown** [mattharrison/IllustratedPy3#181]
p.17:
*  "~~which will~~ *to* bring up Spotlight" - more concise and consistent with the Windows example
* "If, the file" should not have a comma (this is repeated in both the Windows and Mac examples)

p.19: 

* "This window is not a Shell window, it is an *editor* window" -> "This is an *editor* window, not a shell window"

* "hit the F5 ~~button~~ *key*" (and possibly even clarify, "on your keyboard")

p. 22 "With IDLE, it is simple. You just hit F5" could be With IDLE, it is simple: you just hit F5"

**Comment by mattharrison** [comment]
Aug 29
