### ISSUE TITLE
Mention Jupyter and IPython

### ISSUE THREAD

**Issue by jamesscottbrown** [mattharrison/IllustratedPy3#182]
The book mentions neither iPython or Jupyter.

It would be good to at least mention in passing that Jupyter notebooks provide a REPL interface in the browser, and let you save a mixture of code and its output in a notebook format that can be easily shared to others.

It would be also good to mention that the IPython provides an interactive shell that is nicer than that given by the ``python3`` command.

**Comment by mattharrison** [comment]
Aug 29
