### ISSUE TITLE
Windows python PATH

### ISSUE THREAD

**Issue by sembug** [mattharrison/IllustratedPy3#183]
If you had the UAC feature turn on on Windows, the path installed is C:\Users\<username>\AppData\Local\Programs\Python\Python36.

**Comment by sembug** [comment]
![image](https://user-images.githubusercontent.com/30750/29820145-d09f06c0-8c99-11e7-9cf9-5ca424b294a1.png)

**Comment by mattharrison** [comment]
Aug 29
