### ISSUE TITLE
Appendix 28.9

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#191]
This appears to be empty.

Also, you might consider having an appendix of resources.  For instance, you have referred to PEP 8, there's the python.org site, Anaconda, numpy, and many other sites that we as Python programmers commonly reference, and I think it would be helpful to have a list of where those resources are found.  You could probably look at your "favorites" list in your browser of choice for a very good set.

**Comment by mattharrison** [comment]
Aug 29 has an appendix with resources
