### ISSUE TITLE
Ch 25 unanswered questions

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#192]
My fundamental question after reading this chapter remains unanswered.  I don't know if I just didn't comprehend it fully, so take this suggestion with a grain or several of salt.  Why/how does one chose to develop a package versus a module?  Related to that, what is in those mysterious __init__.py files that are in each directory of a package?  What are they doing?

In reading this chapter, I was reliving trying to install python the first time and getting it to work.  I probably had bad instructions, but some told me I had to set/alter sys.path and PYTHONPATH to point to my working directory.   That was daunting and nerve-wracking on my Mac because I didn't want to screw something else up (but I did, and was so thankful for Anaconda).  So I definitely appreciate the points you make that normally we should try to do this (or that was my take away).

**Comment by Rad-Prof** [comment]
Although... both exercises ask the reader to play with sys.path and PYTHONPATH which I am loath to do.

**Comment by mattharrison** [comment]
Does this help? I added this paragraph:


When writing code, which should you prefer a module or a package? I usually
start simple and use a module. When I need to break coherent parts out into their
own modules, then I refactor into a package.

**Comment by Rad-Prof** [comment]
Yes, that is helpful.  It helps us model the thought process in making the distinction.

**Comment by mattharrison** [comment]
Aug 29
