### ISSUE TITLE
26.1 verb tense

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#193]
First sentence should begin with "Below **are** the contents..."

**Comment by Rad-Prof** [comment]
Last sentence of the first paragraph has a typo:  "You can put this **in**..." (currently says "is")

**Comment by Rad-Prof** [comment]
The indentation varies from page 209 to 210 in the cat.py code.

**Comment by mattharrison** [comment]
Aug 29
