### ISSUE TITLE
26.3  Not working for me

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#195]
I created a simple test.py file with the shebang stated (then it just calls print(test) after that).  I wasn't able to call the file by name, and I know that python3 isn't defined on my system so I wanted to see what error I got.  Here's what happened:

MacBook-Pro-3:documents Roger$ test.py
-bash: test.py: command not found
MacBook-Pro-3:documents Roger$ python test.py
test

Is there something else Mac users should know?

**Comment by mattharrison** [comment]
Missing ``chmod +x``? I added that to the note

```
Matts-MacBook-Pro-2:treading-on-python matt$ cat /tmp/test26.py
#!/usr/bin/env python3

print("HELLO THERE!")

Matts-MacBook-Pro-2:treading-on-python matt$ python /tmp/test26.py
HELLO THERE!

Matts-MacBook-Pro-2:treading-on-python matt$ /tmp/test26.py
-bash: /tmp/test26.py: Permission denied

Matts-MacBook-Pro-2:treading-on-python matt$ chmod +x /tmp/test26.py
Matts-MacBook-Pro-2:treading-on-python matt$ /tmp/test26.py
HELLO THERE!

```
