### ISSUE TITLE
26.4 argparse.ArgumentParser

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#196]
Having never used this library before, I am pretty lost reading the example and this chapter.  I wonder if you could comment the code a bit more or explain more so that it is more digestible.  I feel like we just went from crawling to escape velocity in a couple chapters.

**Comment by mattharrison** [comment]
Is it argparse in particular or just walking through the code?

**Comment by Rad-Prof** [comment]
I guess it is how parser, which is really argparse.ArgumentParser() works.  It seems like parser.add_argument is accepting (as its arguments): a command line argument and what to do with it.  But there are some of those lines that have 4 arguments that I just don't get.  Consider the one for '-n', it's not obvious to me what the next argument '--number' does.  I guess I am lazy because I could totally look it up, and maybe that is your intention here, but perhaps including a comment or a Note with an aside about the what lines with parser are doing would be helpful, or maybe just a footnote with what you think is the best reference for is.

**Comment by mattharrison** [comment]
Aug 29 added explanation
