### ISSUE TITLE
Forward (Grammar, etc.)

### ISSUE THREAD

**Issue by wynand1004** [mattharrison/IllustratedPy3#2]
This book will arm you with years of knowledge and
experience are condensed into a easy to follow format. -> This book will arm you with years of knowledge and
experience **that** are condensed into a easy to follow format.

There are **a** different levels of Python. -> There are different levels of Python.

rain dancing - Sorry, not familiar with this expression

By jumping in and actually typing the
examples you will learn a lot more than just reading. -> By jumping in and actually typing the
examples you will learn a lot more than **by** just reading.

**Comment by mattharrison** [comment]
Thanks. Fixed in Aug 12
