### ISSUE TITLE
Chapter 1 (grammar)

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#20]
**Python also scales with age, I have personally seen people from 7-80+ learn basic programming skills using Python.**

There are two sentences here, separated only by a comma. Given the two sentences are closely related and the second expands on the first, both a semicolon and an em dash could be used. Personally I would prefer an em dash.

Python also scales with age—I have personally seen people from 7-80+ learn basic programming skills using Python.
-or-
Python also scales with age; I have personally seen people from 7-80+ learn basic programming skills using Python.
-or-
Python also scales with age. I have personally seen people from 7-80+ learn basic programming skills using Python.

**Comment by mattharrison** [comment]
Thanks. Fixed in Aug14
