### ISSUE TITLE
10.3 easier (and more)

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#202]
>These are two statements, but I typically type them in a single line separated by a semicolon, so I can easier remove it with a single keystroke from my editor when I’m done debugging.

"easier" --> "easily"

The cadence of this sentence naturally ends at "semicolon." Removing the comma flows better, but without it the sentence becomes a run-on. One option—and the one I like best—is to add an em dash. See below.

Lastly, instead of "These are two statements," it might read better to say, "There are two statements here." This one's purely stylistic. I also added "them" to reinforce that you're removing multiple lines.

Altogether:

**There are two** statements **here**, but I typically type them in a single line separated by a semicolon—**that way** I can **easily** remove **them** with a single keystroke from my editor when I’m done debugging.

**Comment by mattharrison** [comment]
Thank you! Aug 29

**Comment by mclaughlin** [comment]
In the 9/2 revision, you have this written as follows:

>**These** are two statements here, but I typically type them in a single line separated by a semicolon—that way I can easily remove them with a single keystroke from my editor when I am done debugging.

Did you intend to say "**These** are two statements here" or "**There** are two statements here"?
