### ISSUE TITLE
Illustration boxes

### ISSUE THREAD

**Issue by rafasysadm** [mattharrison/IllustratedPy3#203]
I would suggest trying to add a background color on the boxes used in the illustrations. I guess it would help highlighting the information and make it easier to spot the details.

Thanks!

**Comment by mattharrison** [comment]
Can you expand a little bit about what you were thinking?

**Comment by rafasysadm** [comment]
I was thinking in something like the example below. As in the "Note" which has a background color highlighting it, I think it would help to highlight the "Objects" illustrations as well.

![image](https://user-images.githubusercontent.com/214601/30007240-9440507e-910a-11e7-8ed9-91676be9e1b0.png)

**Comment by mattharrison** [comment]
Sep 2 Fix
