### ISSUE TITLE
Section 13 and using the not operator

### ISSUE THREAD

**Issue by tudortimi** [mattharrison/IllustratedPy3#208]
In section 12 you mention that the Pythonic way of checking for an allocated object is to do "if object". Later in the section you use something like "if a is None". In section 13 you introduce the "not" operator. It's not really clear to me whether re-writing "if a is None" as "if not a" is Pythonic. It might worth mentioning this explicitly.

**Comment by mattharrison** [comment]
Note added Sep 2
