### ISSUE TITLE
Section 14 - list.append() returns None

### ISSUE THREAD

**Issue by tudortimi** [mattharrison/IllustratedPy3#209]
On page 92, this statement had me scratching my head: "[list.append()] returns None and updates
the list in place.". Seems like this is how Python works, though I can't (easily) find it listed anywhere. This sounds very confusing to someone who programmed in, say, C++, where there are **void** functions.

I would have expected _.append()_ to be such a **void** function. I would have found it helpful to expand a bit on this.

**Comment by mattharrison** [comment]
There are no *void* functions in Python. A list is mutable and calling a method that mutates the list doesn't return the same list. 

I'm not clear on what you found confusing or what you want to expand on.

**Comment by tudortimi** [comment]
The statement _returns None_ was confusing in the beginning. I get that _append()_ updates the list in place, but why does it have to return anything in this case? Is returning _None_ the equivalent idiom to C++'s **void** functions?

**Comment by mattharrison** [comment]
Ah, thanks for clarifying. Yes, there is no way to return nothing from a function. The default return value is None. The function:

    def say_hi():
        print("HI")

Will return None

**Comment by tudortimi** [comment]
There is this sentence "A return statement is not necessary, and if it is missing a function will return None by default." in chapter 17. This comes after the discussion on _append()_, though.

**Comment by mattharrison** [comment]
Thanks. I've added a comment in the section that confused you. Sep 2
