### ISSUE TITLE
6.1 Mutation and state

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#21]
This section talks about Mutation and State.
_Two important programming concepts are state and mutation....._

6.1 Section never talks about how these concepts are related to variables. I was confused to understand why is this in the variables section ? I think it can be confusing to a newbie.

**Comment by Rad-Prof** [comment]
Also confusing is the wording after your command >>> status = "off" when you say "So Python will go _off_ and create ...".  I think it would be less confusing to eliminate the use of the word "off" here.  Just say "So Python will create a little string object containing the three characters _off_ and tag it as _status_."

**Comment by mattharrison** [comment]
@jaypsingh I'm adding this paragraph:

>  How is this related to variables? Remember that in Python everything
>   is an object. Objects have state, and might be mutated. To keep track
>   of these objects, we use variables.
> 

@Rad-Prof thanks I fixed the wording in Aug14 version
