### ISSUE TITLE
14 - Set membership

### ISSUE THREAD

**Issue by tudortimi** [mattharrison/IllustratedPy3#211]
In this section you mention that sets are preferred when checking membership using the **in** operator. Later on, in section 15 on page 110 you do "if name not in ['John', 'Paul']:". Would it have been preferable to say "if name not in { 'John', 'Paul' }:" because this creates a set without first creating a list and converting that?

**Comment by tudortimi** [comment]
Actually, is **in** only defined for sets?

**Comment by tudortimi** [comment]
In section 16 you mention that **in** works for all sequences. Still, is one preferred over the other (list vs. set)?

**Comment by mattharrison** [comment]
There is a *contains* protocol in Python. If a class (set or list, or user defined) implements the ``__contains__`` method (or the iteration protocol), you can use ``in`` with it. Due to how sets are implemented, membership tests against them can be much quicker than a list.

The note at the end of 14.8 briefly mentions the speed issue. Would love your feedback on where specifically I could make the text more clear

**Comment by tudortimi** [comment]
Basically what you mentioned here with implementing the __contains__ would be helpful. In the beginning I was under the impressions that lists are converted to sets in comparisons.

A running theme of Python seems to be that there are these protocols (as you call them) that when implemented interact with language features, such as **in** or **for ... in** and it would be useful, even in a beginner book, to hear about this. I guess you would save how to implement custom versions of them for a more advanced text.

**Comment by tudortimi** [comment]
I did a bit more searching. There is a mention of __iter__ in the summary section for lists and I must have not noticed it. If I read it back now, it's clear that if a class implements this method it can be iterated over. The summary is a bad place to put it, since if I just read the chapter I might skip over it and this is new information.

**Comment by tudortimi** [comment]
Also, __contains__ is mentioned when talking about dictionaries. Maybe the chapter about sets, where **in** is first introduced, would be a better place for it.

Afterwards mentioning that lists also implement __contains__ (or for lists it works because they implement __iter__ and searching can be done naively by searching? - this is what I got from your comment above) would make it clear why they can also be searched for membership using **in**.

Later on for dictionaries **in** means checking whether a key is in the dictionary, because that's what's implemented in its __contains__.

**Comment by mattharrison** [comment]
Great feedback. Thanks! Discussed contains in sets chapter
