### ISSUE TITLE
Chapter 21 - id as constructor argument

### ISSUE THREAD

**Issue by tudortimi** [mattharrison/IllustratedPy3#212]
In the chair example you have the following signature for the constructor: "def __init__(self, id):". Later on you create a chair by calling "Chair(21)" and say you want to number it with 21. The use of "id" is confusing in this case, as the name is loaded with the object "id" (where it's stored in memory). Maybe rename it to something else.

**Comment by mattharrison** [comment]
Added a not Sep 2
