### ISSUE TITLE
Chapters 1-6 comments

### ISSUE THREAD

**Issue by richyvk** [mattharrison/IllustratedPy3#213]
Hi

Firstly can I say I am really enjoying the book! It's well written and has started like no other book I've read so far, namely covering what is really happening under the hood - this is really good I think.

Some comments on the 22/8/17 version - I am a bit slow in reading and note taking so maybe some of this is fixed already?

p13 " Perhaps more interesting is to go
the other way. Run your Python code in the REPL. Your code will
run, but you will have access to the REPL to inspect the state of
your code." - how do you do this?

p15 How do you run the file in IDLE, needs some explanation. Is it what is explained in chapter 4?

A lot is introduced in chapters 1-3 with no explanation. Not necessarily bad, just an observation.

Chap 6 - would like some more explanaiton of reference count, e.g. is it as smple as starting at 1 and adding 1 per reference? Can you access the reference count? (sys.getrefcount())

p30 - typo - num = '400' # now a is a string - should be: now num is a string

p33 "Another method for examining keywords in the REPL is
to type help() then type keywords." - I think this sentence is a bit condusing, perhaps "Another method for examining keywords in the REPL is to type help(keyword)"?

**Comment by mattharrison** [comment]
Thanks. P13 and 15 are explained later in the text. I added a portion regard reference coutning. Fixed p 30 and 33.
