### ISSUE TITLE
Global layout of Illustrated Guides

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#215]
While I find the illustrated guides throughout this book to be very helpful, they consistently seem squished together. As a result it's often difficult to determine if the title below is associated with the drawing above or below. [Here is a modified layout](https://github.com/mattharrison/IllustratedPy3/files/1278375/beg3-aug29_pg66.pdf) that might make it easier to read. Just an idea.

**Comment by mattharrison** [comment]
Awesome! Thanks I have updated all images in Sep 2.
