### ISSUE TITLE
Exercise wording - section 2.4

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#22]
Just for clarity on the second bullet of the exercise on page 7 (section 2.4), you might consider an alternative to the question fragments by starting a sub-bulleted list such as:

If you are used to a particular editor do some investigation into its support for Python.  For example, does it:
- Perform syntax highlighting?
- Run your code in a REPL for you?
- Provide a debugger for stepping through your code?

**Comment by mattharrison** [comment]
Fixed in Aug 14
