### ISSUE TITLE
12.2 Booleans

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#220]
>You can also use assign those values to variables:

You can also ~~use~~ assign those values to variables:

---

>However, this is usually unnecessary due to implicit casting Python when conditionals are evaluated.

However, this is usually unnecessary due to implicit casting Python **performs** when conditionals are evaluated.

---

>It is common to hear in Python parlance of objects behaving as “truthy” or “falsey”—that means that non-boolean types can implicitly behave as though they were booleans.

**In Python parlance, it is common to hear** of objects behaving as “truthy” or “falsey”—that means that non-boolean types can implicitly behave as though they were booleans.

---

>Since an nonempty string behaves as truthy, you can test whether a string, name, has content with the code below.

Since ~~an~~ **a** nonempty string behaves as truthy, you can test whether ~~a~~ **the** string, name, has content with the code below.

---

>Python will evaluate the contents of the if statement, and coerce to a boolean for you, and because a string is True when it has content you only need if name:. 

The end of this sentence may confuse people until they see the following context. Add quotation marks or a more noticeable font change to clarify.

Python will evaluate the contents of the if statement, and coerce to a boolean for you, and because a string is True when it has content you only need **"if name:".**

-or-

Python will evaluate the contents of the if statement, and coerce to a boolean for you, and because a string is True when it has content you only need ``if name:``.

---

>For the built-in types, int, float, str, and bool, are classes. Even though their capitalization (lowercase) makes it look as if they were functions, they are classes. Invoking help(str) will confirm this:

This should be "case (lowercase)" as capitalization does not include it's opposite (non-capitalized, lowercase, etc.).

So instead:

For the built-in types, int, float, str, and bool, are classes. Even though their ~~capitalization~~ **case** (lowercase) makes it look as if they were functions, they are classes. Invoking help(str) will confirm this:

---

> If you wish to define the implicit truthiness for self defined objects, the .\_\_bool\_\_ method specifies this behavior. It can return True, or False. If this magic method is not defined, the .\_\_len\_\_ method is checked for a non-zero value. If neither method is defined, an object defaults to True. 

While it may be too advanced at this point in the book, I think it would help to include an example of this further in--maybe in chapters 21 or 22--and reference it here. But I'm guessing that for most readers at this point, the concept of defining magic methods would prove too abstract to gain much without an example. Just a thought.

**Comment by mattharrison** [comment]
Thanks for the great feedback. Sep 5
