### ISSUE TITLE
23.7 Wrapping exceptions - function name

### ISSUE THREAD

**Issue by willingc** [mattharrison/IllustratedPy3#221]
I love that you are covering wrapping exceptions. I found the function name `work` a bit confusing. `divide_work` might be a better name.

### First example

A better error message may be helpful to reinforce later in the example that the cloud service is down.

```
def log(msg):
    raise SystemError("Logging service is down and unavailable.")
```

> When you call work, Python will show two errors, the Zero- DivisionError, and the SystemError.

Perhaps:

When you call `divide_work` with 5 as the numerator and 0 as the denominator, Python will show ...

### Second example

I'm not quite sure why the `log` function has changed. Perhaps will confuse those new to Python.

> You will still see two exceptions, but the ArithmeticError doesn’t shadow the original ZeroDivisionError:

Perhaps: 

You will see two exceptions now: the original ZeroDivisionError and the ArithmeticError which is no longer shadowed by the ZeroDivisionError.

### Last example

> Now you only see the outermost error:

Perhaps:

Now you only see the outermost error, ArithmeticError:

### Section 23.9 Typo

The various mechanisms for catching errors, raising them, and re-raising them ~~was~~ were discussed.

**Comment by mattharrison** [comment]
Awesome! Fixed in Sep 5
