### ISSUE TITLE
25.4 PYTHONPATH - Clarify with more emphasis

### ISSUE THREAD

**Issue by willingc** [mattharrison/IllustratedPy3#223]
> PYTHONPATH is an environment variable listing non-standard directories that Python looks for modules or packages in. This variable is usually empty. It is not necessary to change PYTHONPATH unless you are developing code and want to use libraries that have not been installed.

I would recommend really stressing that the variable is usually empty. Perhaps add a tip to leave it empty unless you have a good reason to change it.

**Comment by mattharrison** [comment]
Tip added. Sep 5
