### ISSUE TITLE
12.5 Exercise 3 and 4

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#225]
## 12.5 Exercise 3

>3. Create a list, names, with the names of people in a class. Write code to print The class is empty!, or Class has enrollments., based on whether there are values in the names list. (See the tip in this chapter for details).

Since you're having the reader print strings, I think **'The class is empty!'** and **'Class has enrollments.'** should have quotes around them. This would improve the readability of this exercise.

Also, once you've established that 'names' is a list, I think you should refer to it like this:

3. Create a list, ``names``, with the names of people in a class. Write code to print 'The class is empty!', or 'Class has enrollments.', based on whether there are values in ~~the~~ ``names`` ~~list~~. (See the tip in this chapter for details).

## And same for 12.5 Exercise 4

4. Create a variable, ``car``, set to ``None``. Write code to print **'Uber for you!'**, or **'You have a car!'**, based on whether or not ``car`` is set (``None`` is not the name of a car).

**Comment by mattharrison** [comment]
Thanks Sep 5
