### ISSUE TITLE
Whitespace or not (start 5.2)

### ISSUE THREAD

**Issue by hopper22** [mattharrison/IllustratedPy3#226]
Section 5.2 is, I think  the first time a variable is assigned a value.  As a complete Py newbie, I was wondering whether the whitespace between the '=' was needed, or why you used it. 3.2 make a big deal aout

**Comment by hopper22** [comment]
about no space in a function (sorry for messy comment)

**Comment by mattharrison** [comment]
Added a bit about the spaces not being required but added  for readability. Sep 5 update
