### ISSUE TITLE
ch6

### ISSUE THREAD

**Issue by vahtras** [mattharrison/IllustratedPy3#230]
This is a great chapter describing the nature of assignment and variables. 

One comment. I know that it is often said that *Everything in Python is an object*. But what does that mean and is it true? If a reader does not know what an object is then the statement does not mean anything. If there is nothing that is *not* an object there is nothing to compare to... And what about  keywords? If you try something like

```
>>> id(break)
  File "<stdin>", line 1
    id(break)
           ^
SyntaxError: invalid syntax
```
you get a syntax error. Right, `break` maybe is not an object with an identity and type.. so maybe not everything is an object :-)

**Comment by mattharrison** [comment]
Sep 5 added disclaimer
