### ISSUE TITLE
Exercise 3.4.2 / Open/ Save/ Module definition

### ISSUE THREAD

**Issue by hopper22** [mattharrison/IllustratedPy3#232]
Ex 3.4.2 Up to this point, you haven't explained how to save, or how "execute' or "run / F5".  Indeed (as a newbie) trying to figure it out myself in IDLE, the only option I saw was "Run/ Run Module'.  Clearly that's what you mean. You DO mention most of this next chapter (Ch4), but don't mention an independant "Save" or "SaveAs" step.  Files are saved after a prompt following an attempt to run.  Do we "open" or "open module".    Does it matter?  What is a module?  You say 'module is defined later (Ch 25??).  The word is used, but is it really defined ?  Still not clear module vs package,  Are modules small self contained code, that can be brought together (packaged) to make a more complicated program i.e a package?   Does  PEP8 define these words (ie you recite PEP8 (25.1) for filenaming, does PEP8 define module/package meaning ?)

**Comment by mattharrison** [comment]
Good suggestion. Replaced 3.4.2 with a chapter appropriate exercise. Sep 5
