### ISSUE TITLE
13.4 More choices

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#234]
>Python will start from the top trying to find a statement that evaluates to **True ,** when it does, it runs the block then continues executing at the code following **the all** of the blocks.

I'm guessing "the all of the blocks" was intended to be "all of the blocks" (see below). Also, you have an extra space after "evaluates to True" before the comma (at least that's how it copies/pastes)...but since these are two independent clauses, I broke them into two sentences.

Python will start from the top trying to find a statement that evaluates to **True. When** it does, it runs the block **and** then continues executing at the code following **~~the~~** all of the blocks.

**Comment by mattharrison** [comment]
Thanks Sep 5
