### ISSUE TITLE
14.1 Lists - verb forms

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#235]
>There are two ways to create empty lists, one is to invoke the list class, and the other is using the square bracket literal syntax— [ and ] :

You're mixing verb forms.

Infinitive:
"**to invoke** the list class"

Participle:
"the other is **using** the square bracket literal syntax"

It reads better if you pick one:

There are two ways to create empty lists, one is **to invoke** the list class, and the other is **to use** the square bracket literal syntax— [ and ] :

**Comment by mattharrison** [comment]
You are awesome! Sep 5
