### ISSUE TITLE
Chapter 4 - Note on hello.py failing

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#24]
The third Note in the chapter needs more explanation for newbies.  I suggest:

Note
The previous command, python3 hello.py, will probably fail unless you have a file named hello.py _in your current directory_.

The note can also be misleading because some folks won't have to type python3, but could just as easily use python hello.py.  You also may need more than a note to explain how to find the current directory of the terminal window or how to navigate to the director you want.  So, I'm thinking this might warrant more than just a short note but an entire paragraph or even section.

**Comment by mdbaggy** [comment]
Yeah I struggled a bit getting  that to work, had to do some looking up to figure it out. Agree a note on navigating directories would be useful.

**Comment by mattharrison** [comment]
@mdbaggy do you have more details on what happened to you? What platform are you on? What error did you see? What web page ended up helping you,

**Comment by mdbaggy** [comment]
@mattharrison Im using Ubuntu 16.04. To get a quick answer to using directories in terminal I just watched a vid on you tube.

This is the original error when I couldnt navigate to the dir.
![image1](https://user-images.githubusercontent.com/30999738/29283321-266f5758-811e-11e7-83d7-018548f27621.JPG)

After finding how to navigate to correct dir this is what I did.
![image2](https://user-images.githubusercontent.com/30999738/29283432-91b73990-811e-11e7-90a1-79c5a890a3e6.JPG)

The part thats confusing - Will it still not run from the home directory -$ ? From reading the chapter I understood it that once **$ chmod +x hello.py** was applied to the file it would run from the home dir ?
![image3](https://user-images.githubusercontent.com/30999738/29283719-cba6f1da-811f-11e7-99f5-207f0d2cf46e.JPG)

I apologise in advance if its me as im making things more difficult by being new to linux and python

**Comment by mattharrison** [comment]
Hmmm, maybe I'll add an appendix about dealing with file navigation.

**Comment by EmadMokhtar** [comment]
@mattharrison Yes, it's taking so much space and I think making a separate appendix for it is better.

**Comment by mattharrison** [comment]
Added appendix Aug 29
