### ISSUE TITLE
14.8 Sets Note 1

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#243]
>Because sets must be able to compute a **hash value** for items in the set, they can only contain items that are **hashable.** In Python, mutable items are not **hashable.** This means that you cannot hash a list or dictionary. To **hash** your own user created classes, you will need to implement __hash__ and __eq__.

You may have already mentioned them in a previous chapters, but if not it might be worthwhile to define **"hash," "hash value,"** and **"hashable."** You do refence them in context, however someone new to these terms may not understand.

**Comment by mattharrison** [comment]
Sep 5
