### ISSUE TITLE
15.5 subsequent loop

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#245]
>In a subsequent loop over only the items that need to be deleted (names_to_remove), remove them from the original list—names:

This is not a complete sentence, and while the meaning is clear from context, in its current form it is confusing. Also, for consistency I replaced the em dash at the end with parentheses, as your reference to the first list was parenthetical.

In a subsequent loop, iterate over only the items that need to be deleted (names_to_remove), and remove them from the original list (names):

**Comment by mattharrison** [comment]
Good find. Thanks Sep 5
