### ISSUE TITLE
Chapter 5 Note is confusing

### ISSUE THREAD

**Issue by EmadMokhtar** [mattharrison/IllustratedPy3#246]
In Chapter 5 the variable conversion from str to int or float note is confusing, because in the text you mentioned the issue and the solution, then in code you mentioned the issue and the solution.

My suggested order is:

- Text (issue)
- Code (issue)
- Text (solution)
- Code (Solution)

**Comment by mattharrison** [comment]
Sep 5

**Comment by EmadMokhtar** [comment]
@mattharrison Is this mean solved in Sep 5 already? if yes, I found this in Sep 5 version `beg3-sep5.pdf` on Dropbox.

**Comment by mattharrison** [comment]
Sorry my bad. The next version fixed that
