### ISSUE TITLE
Chapter 6: Figure 6.1 is cutting one note.

### ISSUE THREAD

**Issue by EmadMokhtar** [mattharrison/IllustratedPy3#247]
In Chapter 6 the note about `getrefcount`, Figure 6.1 is cutting the note in half.

**Comment by mattharrison** [comment]
Sep 5

**Comment by EmadMokhtar** [comment]
@mattharrison Is this mean solved in Sep 5 already? if yes, I found this in Sep 5 version beg3-sep5.pdf on Dropbox.

**Comment by mattharrison** [comment]
My bad. The version following Sep 5 fixed it
