### ISSUE TITLE
16.1 Implicit hierarchy

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#249]
>info = {'name': 'Pete', 'last': 'Best'}

Using hierarchical terms like 'name' and 'last'—where 'last' may be abstracted as a subset of 'name'—may present difficulty for a reader new to this construct. To lower the boundary for comprehension I would recommend keeping these terms as flat as possible.

**Example:**

info = {'first': 'Pete', 'last': 'Best'}

-or-

info = {'first_name': 'Pete', 'last_name': 'Best'}

**This would also affect figure 16.1:**

>first = 'Peter'
>
>info = {'name' : first}

first = 'Peter'

info = {'first_name': first}

**Comment by mattharrison** [comment]
Thanks Oct1
