### ISSUE TITLE
5.4 second exercise

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#25]
I think the second exercise might be pretty challenging given that (I think) it would require new programmers to know how to convert an integer to a string and how to concatenate strings.  Consider changing this exercise to one where it asks the user their name, then their age and then prints "XXXX you are currently ### years old."  In the exercise, you could give the forward looking hint that the + operator can be used to concatenate strings.

**Comment by mattharrison** [comment]
Thanks for the feedback. I'll add an example in the next version of using ``print`` with strings and numbers (separated by commas). No need for concatenation yet. The example right before the exercise shows converting strings to ints, so I don't think this should be too challenging.

**Comment by Rad-Prof** [comment]
It's true that they have seen int() casting, but they haven't seen str().  Since print(age+1) would work, you are probably right.  I thought you wanted them to do something like print('You will be '+str(age+1)+' next year.).

**Comment by Rad-Prof** [comment]
Oops.  Missed a quote mark, but you get my point.

**Comment by mattharrison** [comment]
Yep, point taken. Going to close this for now unless I hear others complaining here.
