### ISSUE TITLE
6.2 sys.getrefcount (reminder ?)

### ISSUE THREAD

**Issue by hopper22** [mattharrison/IllustratedPy3#251]
The challenge here is that, on my IDLE, `sys` is not installed and needs 'import'.  You did mention `sys` and `import`  in 3.2.  Maybe helpful to have a little reminder here showing code ` import sys `   `sys.getrefcount(variable)`  - it would be nice consolidation of these (book-wise) new concepts.

**Comment by mattharrison** [comment]
Good point. Fixed in Oct 2.
