### ISSUE TITLE
8.2, 9, 11.2

### ISSUE THREAD

**Issue by hopper22** [mattharrison/IllustratedPy3#255]
A few more instances when new topics arise and 'threw off' my smooth reading .  Note in 8.2 re coercion.  example: the `%s` (variable) treatment just appears : confusing for a newbie where `%` was (a moment ago modulo).  The description re "left operand" is also not clear, imho. Could not figure out operand at all, and if its the modifier eg %s %r, its on the r.h.s.  Suggest something like "In chapter 9 we will talk more about the special uses of %, when linked to modifiers, to pass values and formatting into a function.".   Chapter 9, "regular expression" appears (only time in book, not defined). Something like "Programmers in many languages use 'regular expressions' to find and modify sequences of characters such as phone numbers, name etc.  We don't have room here but there are plenty of resources [internet?] to get started with this powerful tool".  Chapter 11.2, you show` endswith` (default function) and then example with indexed positions [0,3].  ie the `startswith` function which also has indexed features.  "Python has a related function 'startswith' which tries to match a test string against the beginning of a string." Maybe continue [the default values of 'startswith' and 'endswith' test the beginning and end parts of a string respectively. However, using indexed values, both functions will return the same result." [+ exercise ?]

**Comment by mattharrison** [comment]
Thanks. Addressed issues in Oct 2
