### ISSUE TITLE
16.7 Dictionary iteration

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#256]
>If you materialize the view into a list, you will see that the list is a sequence of key, value tuples. (The same thing that dict accepts to create a dictionary!):

Since the parenthetical note modifies the sentence before it, I would at least drop the period after "tuples" and lower the case on "The."

Or better yet, use an em dash and drop both the parentheses and the exclamation point—this is equally emphatic, yet much cleaner. Also, you might consider adding parentheses around (key, value) tuples.

If you materialize the view into a list, you will see that the list is a sequence of (key, value) tuples—the same thing that dict accepts to create a dictionary:

**Comment by mattharrison** [comment]
Thanks Oct 2
