### ISSUE TITLE
16.7 Note Parentheses

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#257]
>Typically, you don’t mix key types, because it is confusing to readers of the code and also makes sorting keys harder. **(Python 3 won’t sort mixed type lists without a key function telling Python explicitly how to compare different types.)** This is one of those areas where Python gives you the ability to do something, but that doesn’t mean you should. In the words of Python core developer Raymond Hettinger:

Parentheses aren't needed here. The sentence following the parentheses is germane, so I think it flows well without them.

Typically, you don’t mix key types, because it is confusing to readers of the code and also makes sorting keys harder. Python 3 won’t sort mixed type lists without a key function telling Python explicitly how to compare different types. This is one of those areas where Python gives you the ability to do something, but that doesn’t mean you should. In the words of Python core developer Raymond Hettinger:

**Comment by mattharrison** [comment]
Thanks Oct 2
