### ISSUE TITLE
17 Functions Intro

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#259]
>You have come a long way without discussing functions, which are a basic building block of Python programs.

Given you refer to the text in the context of a discussion, first-person (plural) is more fitting:
You --> We

**We** have come a long way without discussing functions, which are a basic building block of Python programs.

>Whenever you see a colon in Python, you should immediately think the colon is followed by an indented block. (This is similar to the body of the for loops shown previously.)

This first sentence is the antecedent of the subject in the parenthetical clause ("This"), so you might consider using a semi-colon or an em dash to more clearly connect the two. If you use an em dash, there's no longer the need to keep "this is," and removing it further strengthens the sentence.

Whenever you see a colon in Python, you should immediately think the colon is followed by an indented block; this is similar to the body of the for loops shown previously.

-or-

Whenever you see a colon in Python, you should immediately think the colon is followed by an indented block—similar to the body of the for loops shown previously.

...or at the very least, move the parenthetical clause within the punctuation of the first sentence:

Whenever you see a colon in Python, you should immediately think the colon is followed by an indented block (similar to the body of the for loops shown previously).

**Comment by mattharrison** [comment]
Oct2
