### ISSUE TITLE
6.6 Tip

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#26]
This tip right before section 6.7 could be misconstrued.  I'd replace the word "good" with "tempting" as a description of variable names. It definitely would not be GOOD for programmers to use those words as variable names.  I'd also probably add "max", "min" and "range" to the list you have, but maybe just because I'm a mathematician and so I do a lot of computational programming.

**Comment by mattharrison** [comment]
Thanks fixed in Aug 14 version
