### ISSUE TITLE
19.7 Designing around files

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#266]
>At first thought it might seem that you want the _API_ (application programming interface) for your functions to accept the filename of the file that you want to modify, like this:

No need to italicize:
_API_ --> API

At first thought it might seem that you want the **API** (application programming interface) for your functions to accept the filename of the file that you want to modify, like this:

>But what will happen when the requirement comes to insert line numbers in front of lines not coming from files?

"the requirement comes to insert" --> "you're required to insert"

"not coming from files" --> "from a source other than a file"

But what will happen **when you're required to insert** line numbers in front of lines **from a source other than a file**?

>Or if you want to test the code, now you need to have access to the file system.

Or if you want to test the code, now you need ~~to have~~ access to the file system.

>One solution to these issues is to refactor the ``add_numbers`` function so that it only opens the file in a context manager then calls another function, ``add_nums_to_seq`` .

- "to these issues" is implied
- add "will"
- missing conjunction ", and"
- "opens" --> "open" and "calls" --> "call"
- superfluous space between ``add_nums_to_seq`` and period

One solution ~~to these issues~~ is to refactor the ``add_numbers`` function so that it **will** only open~~s~~ the file in a context manager, **and** then call~~s~~ another function, ``add_nums_to_seq``**[remove space here]**.

**Altogether:**

At first thought it might seem that you want the API (application programming interface) for your functions to accept the filename of the file that you want to modify, like this:

-and-

This code will work okay. But what will happen when you're required to insert line numbers in front of lines from a source other than a file? Or if you want to test the code, now you need access to the file system. One solution is to refactor the ``add_numbers`` function so that it will only open the file in a context manager, and then call another function, ``add_nums_to_seq``.

**Comment by mattharrison** [comment]
Oct2
