### ISSUE TITLE
20 Unicode Intro

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#269]
>**You’ve** seen strings all over the place, but **you** haven’t really talked about one of the biggest changes that came in Python 3, Unicode strings!

The reader isn't talking:
"You've" --> "We've"
"you" --> "we"

**We’ve** seen strings all over the place, but **we** haven’t really talked about one of the biggest changes that came in Python 3, Unicode strings!

>Python 2 had support for Unicode but you needed to explicitly create them.

Missing antecedent of "them":

add: "strings,"

Python 2 had support for Unicode **strings,** but you needed to explicitly create them.

**Comment by mattharrison** [comment]
Oct 2
