### ISSUE TITLE
23.3 Multiple exceptional cases.

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#27]
In section 23.3 header says **Multiple _exceptional_ cases.**
Is it intentional or did you mean **23.3 Multiple _Exception_ cases.**

This section also talks about "The argparse module from the standard library provides an easy way to parse command line option....", which i also felt is not relevant to multiple exceptions. 

The example code uses raise exceptions as shown in below code:
_raise ArgumentError(action, msg % type_func)_

I see you are talking about raising exception in further section 23.6. So i would suggest if we can move this block of code to appropriate section, it would help. It might add confusion for a newbie.

![23 3_exception_1](https://user-images.githubusercontent.com/15726294/29282489-027e6eba-80f1-11e7-97b4-9624fec9ce94.PNG)

**Comment by mattharrison** [comment]
Fixed the spelling.

The argparse module in the standard library is listed as an example of dealing with multiple exception types. I'm going to close this issue unless someone else claims it is confusing.
