### ISSUE TITLE
20.1 Unicode glyph not mapping properly

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#270]
It appears the unicode for the GRINNING FACE glyph isn't mapping properly in Mac OS Preview (version 909.18)—probably a font issue.

![unicode copy](https://user-images.githubusercontent.com/3707913/31460471-6e9e99be-ae7b-11e7-9896-804a4d58978c.png)

**Comment by mclaughlin** [comment]
Given that this is likely just a case where I don't have the font installed that you used in the book, 
 and the font that Preview is substituting does not support that glyph, what do you plan to do for the digital copy of this book? Or maybe a better question is to ask, do you plan to distribute the book digitally? And if so, how will you get past this font issue?

**Comment by mattharrison** [comment]
This is my issue. I need to get that glyph into xelatex...

**Comment by mattharrison** [comment]
https://tex.stackexchange.com/questions/395941/insert-an-emoticon-using-xelatex

**Comment by mattharrison** [comment]
Oct 2
