### ISSUE TITLE
Figure 20.1 Subtitle

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#271]
>You can use a glyph, code point (if it has more than 4 digits, you need to use capital U and left pad with 0 until you have 8 digits), or the name. Also shown is decoding the UTF-8 byte string to the glyph.

- Given the length of the parenthetical clause after "code point", I recommend you move "code point" to the end of the list, and the parenthetical clause to a separate sentence.
- "has **more** than four digits" --> "has **less** than four digits"
- "need to use capital U" --> "need to prefix it with a capital U"
- "left pad with 0" --> "left-pad it with 0"
- "shown is decoding" --> "shown is an example decoding"
- "glyph." --> "corresponding glyph."

You can use a **glyph, the name, or the code point. If the code point** has **less** than 4 digits, **you need to prefix it with a capital U** and **left-pad it** with 0 until you have 8 digits. Also shown is **an example** decoding the UTF-8 byte string to the **corresponding** glyph.

**Comment by mattharrison** [comment]
Oct 2
