### ISSUE TITLE
20.2 Basic steps in Python

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#273]
>Note that this string is the same as the **prior** string:

I'm fairly certain this is simply a personal style preference. In general I think of "prior" as referring to something that occurred in the past, and "previous" relating both to an object (or event) ordered earlier in a sequence. But I can't really back this up substantively. :)
"prior" --> "previous"

Note that this string is the same as the **previous** string:

>But if you don’t speak native Unicode, or have font support, it is perhaps the most readable.

Either remove the comma after "Unicode", or make the negative verb ("don't have") more explicit in the second clause.

But if you don’t speak native Unicode or have font support, it is perhaps the most readable.
-or-
But if you don’t speak native Unicode, or don't have font support, it is perhaps the most readable.

**Figure 20.02:**

>Image illustrating encoding a Unicode string to a byte representation. In this case, you convert to UTF-8. There are other byte encodings for this string. If you have a UTF-8 byte string, you can decode it into a Unicode string. Note that you should be explicit about the decoding as there are potentially other encodings that you could decode to that might give use erroneous data, or mojibake.

Lots of changes:

Image illustrates the encoding (in this case using UTF-8) of a Unicode string into its byte representation, and then the decoding of the same byte string back into Unicode (also using UTF-8). Note that you should be explicit when decoding as there are other encodings that if used, might produce erroneous data or mojibake (character transformation).

**Comment by mattharrison** [comment]
Oct 2
