### ISSUE TITLE
20.5 Unicode and files

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#274]
>Likewise, you can specify the encoding when you open a file **to write strings to**.

"to write strings to" --> "for writing"

Likewise, you can specify the encoding when you open a file **for writing**.

>Remember, you should treat encodings as a serialization format.

It might be good to give a little context here, as the reader may not know what "serialization" is or how it pertains to the storage/transmission of encoded data.

 >**I’ll write** the Unicode string as UTF-8 (the default on the author’s machine) and CP949 (Korean):

Avoid first person singular pronouns:

Here are two examples of writing to a file. With the first file no encoding is defined, and it therefore defaults to UTF-8 (per the system's default encoding). In the second example, CP949 (Korean) is set as the encoding parameter.

>If you are dealing with text files that contain non-ASCII characters, make sure you specify **your** encoding.

"your" --> "their"

If you are dealing with text files that contain non-ASCII characters, make sure you specify **their** encoding.

**Comment by mattharrison** [comment]
Oct 2
