### ISSUE TITLE
Figure 21.1 subtitle

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#275]
>Figure 21.1: A figure illustrating a string object. Note that an object has a type. Really, this type is the class of the object.

This figure is already labeled a figure, so no need to refer to as one.

"A figure illustrating" --> "This illustrates"

Figure 21.1: This illustrates a string object. All objects have types, which are really just the class of the object. In this case the class is 'str'.

**Comment by mattharrison** [comment]
Oct 2
