### ISSUE TITLE
21.1 Planning for a class

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#277]
>Assume that you work for a ski resort and want to model how people use the **ski lifts**. One way to do so would be to create a class that defines a chair on a **ski chairlift**.

Although you define "chairlift," you refer to it both as **"ski lifts"** and a **"ski chairlift"**. To reduce confusion keep this reference consistent. Or, you might first refer to it as a "ski chairlift" and then drop "ski" in your second mention.

"the ski lifts" --> "the ski chairlifts"
"chair on a ski chairlift" --> "chair on a chairlift"

Assume that you work for a ski resort and want to model how people use **the ski chairlifts**. One way to do so would be to create a class that defines a **chair on a chairlift**.

>For other people that might matter.

Reorder or add comma, otherwise it sounds like an incomplete sentence where the "other people" are the ones that "might matter." Or you could drop this sentence completely, as it's not really needed.

For other people, that might matter.
-or-
That might matter for other people.

>You can dive in a little deeper, capacity can be broken down into maximum capacity and current occupants.

You have two separate sentences here.

To ~~You can~~ dive in a little deeper, capacity can be broken down into maximum capacity and current occupants.

**Comment by mattharrison** [comment]
Oct 2
