### ISSUE TITLE
21.3 Creating an instance of a class

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#280]
>Python assigns the __class__ attribute of the object to the Chair class before passing it into the constructor.
 
I might just be confused here, but this seems backwards. Did you mean:

Python assigns the __class__ attribute **~~of~~ to** the object **~~to~~ of** the Chair class before passing it into the constructor. 

-or, to flip it around--

Python assigns the __class__ attribute of the Chair class to the new object before it passes it into the constructor.

>Remember that objects store state, and mutate the state.

"store state, and mutate the state" --> store and mutate state"

Remember that objects store and mutate state.

>When you invoke the class (i.e. put parentheses after the class name), you tell Python that you want to call the constructor:

Although you touch on this here, it might be worth mentioning the simplicity of python class instantiation, as readers coming from other languages may be accustomed to a more verbose syntax to create objects.

>max_occupants attribute is actually stored on the class, but you can access it from the instance:

This might be a great place to mention scope/namespaces again.

**Comment by mattharrison** [comment]
Oct 2
