### ISSUE TITLE
Chapter 2 - Which version of Python? (grammar)

### ISSUE THREAD

**Issue by davebrochu** [mattharrison/IllustratedPy3#29]
You have the following sentence.

In fact, most of the content in this book is
perfectly applicable to Python 2, if you want to focus on Python 2,
check out prior versions of this book.

You should probably make this into two sentences. Note the period between 2 and If
In fact, most of the content in this book is
perfectly applicable to Python 2. If you want to focus on Python 2,
check out prior versions of this book.

**Comment by mattharrison** [comment]
Thanks. Fixed in Aug14
