### ISSUE TITLE
23.2 Easier to ask for forgiveness

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#291]
>If it is included then e (or whatever you choose as a valid variable name) will point an instance of a ZeroDivisionError exception.

Missing preposition:
"will point an instance" --> "will point **to** an instance"

If it is included then e (or whatever you choose as a valid variable name) will point **to** an instance of a ZeroDivisionError exception.

>If you leave `as e` off the end of the except statement, you will still have an active exception, but you won’t be able to access the instance of it.

This sentence is difficult to read because `as e` is not clearly differentiated from the primary font.

**Comment by mattharrison** [comment]
Added quotes around `as e`. Oct 2
