### ISSUE TITLE
24.2 Tip [#]_

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#294]
>Users of the **Numpy[#]_** library have adopted the standard of reducing keystrokes by using a two-letter acronym:

Are the [#]_ characters supposed to be here? Should I ignore these when I see them?

**Comment by mclaughlin** [comment]
Also in 25.2:

>Here is an example from the directory layout of the popular **SQLAlchemy[#]_**

**Comment by mattharrison** [comment]
Fixed in Oct 2
