### ISSUE TITLE
26.4 Note 2 [#]_

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#298]
Characters [#]_ in note.

![26-4-note2](https://user-images.githubusercontent.com/3707913/31741999-1bf2913a-b40b-11e7-9caf-e7a20866c769.jpg)

**Comment by mclaughlin** [comment]
Also notice the double backticks after **venv** and before **PATH**.

**Comment by mattharrison** [comment]
Oct 2
