### ISSUE TITLE
Chapter 1 (Grammar)

### ISSUE THREAD

**Issue by wynand1004** [mattharrison/IllustratedPy3#3]
It is the top language being taught in the
university. -> It is the top language being taught in
universities.

Python enables productivity. -> Python enables **increased** productivity.

if you have some
experienced in programming -> if you have some
**experience** in programming

*Some of these suggestions or stylistic rather than grammer.  Let me know if you'd like me to be less pedantic about it.

**Comment by mattharrison** [comment]
These are great. Fixed Aug 12
