### ISSUE TITLE
Chapter 3 - 3.2 footnote missing

### ISSUE THREAD

**Issue by davebrochu** [mattharrison/IllustratedPy3#30]
On page 10, you reference a footnote (6) that does not exist

![image](https://user-images.githubusercontent.com/2998166/29297488-53e947d2-812f-11e7-9ccf-2d0879e7d169.png)

**Comment by davebrochu** [comment]
The footnote actually appears on page 11 instead of 10

**Comment by mattharrison** [comment]
Aug 29 fix
