### ISSUE TITLE
26.11 Testing

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#300]
>In addition, Python includes a library, doctest, that allows **testing and validation of Python REPL snippets.**
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Another nice feature of doctest is **validation of documentation**.

These two sentences seem redundant, especially if the primary purpose of **"Python REPL snippets"** within docstrings is **"documentation."**

**Comment by mattharrison** [comment]
Oct 2
