### ISSUE TITLE
Foreword

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#305]
>Rather than taking months reading blogs and websites and searching mailing lists and groups, this book will allow a programmer to quickly ~~feel~~ knowledgeable and comfortable with Python.

"quickly feel knowledgeable" --> "quickly become knowledgeable"

Rather than taking months reading blogs and websites and searching mailing lists and groups, this book will allow a programmer to quickly **become** knowledgeable and comfortable with Python.

>A recommended approach for learning the language is to read a chapter then actually sit down at a computer and type out some of the examples found in the chapter.

"chapter then actually sit " --> "chapter and then sit"

A recommended approach for learning the language is to read a chapter **and** then sit down at a computer and type out some of the examples found in the chapter.

**Comment by mattharrison** [comment]
Oct 2
