### ISSUE TITLE
Chapter 1 Intro

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#306]
>Enterprises have also converged on Python. They want to take advantage of Python as well.

This should be one sentence:

Looking to take advantage of its power and efficiency, enterprises have also converged on Python.

>At work, I was tasked to work with a co-worker who was well versed in Tcl.

Using "work" twice so close together doesn't flow well. How about something like this:

At work, I was assigned to a team with a co-worker who was well versed in Tcl.

>At work, I was tasked to work with a co- worker who was well versed in Tcl. Neither wanted to jump ship though both of us were interested in learning Python.

Of the two clauses in the first sentence there are two subjects "I" and the pronoun "who" and two direct objects "co-worker" and "Tcl." As a result, the antecedent to the word "Neither" (in the second sentence) is initially unclear. Is it "I" and the "co-worker" or the "co-worker" and "Tcl."

Context does help the reader here, but to be more explicit add "of us":

"Neither wanted" --> "Neither of us wanted"

Neither **of us** wanted to jump ship though both of us were interested in learning Python.

And together:

At work, I was assigned to a team with a co-worker who was well versed in Tcl. Neither **of us** wanted to jump ship though both of us were interested in learning Python.

**Comment by mattharrison** [comment]
Oct 2
