### ISSUE TITLE
2.2 REPL Footnote 4

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#307]
><sup>4</sup>REPL stands for Read, evaluate, print, and loop. You will soon see an example of using it.

- Add title case on "evaluate, print, and loop" or drop on "Read".
- Remove "of"

<sup>4</sup>REPL stands for Read, Evaluate, Print, and Loop. You will soon see an example **~~of~~** using it.

-or-

<sup>4</sup>REPL stands for [Read–Eval–Print Loop](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop). You will soon see an example using it.

**Comment by mattharrison** [comment]
Oct 2
