### ISSUE TITLE
Chapter 2 - 2.4 Exercises (language)

### ISSUE THREAD

**Issue by paul-clearspace** [mattharrison/IllustratedPy3#31]
2.4 Exercises
1. Install Python 3 on your computer.
2. Investigate your favorite editor. Does it support Python? Does it highlight syntax? Run code in a REPL? Provide a debugger?

Previous copy
2.4 Exercises 
• Install Python 3 on your computer. 
• If you are used to a particular editor, do some investigation into its support for Python. Does it do syntax highlighting? Run your code in a REPL for you? Provide a debugger for stepping through your code?

**Comment by mattharrison** [comment]
Thanks fixed in Aug 14
