### ISSUE TITLE
Chapter 4.1 - Confusing wording

### ISSUE THREAD

**Issue by davebrochu** [mattharrison/IllustratedPy3#32]
The last paragraph in section 4.1 reads

This might seem trivial, but the shell window now has the state
of your code. In this case we only printed to the screen, so there is
not much state. In future examples we will see how we can use the
integration between the editor and shell to provide an environment
where we can quickly try out code, see the results, **and inspect what
out program.**

I'm not sure what you are trying to convey with "and inspect what out program"

**Comment by mattharrison** [comment]
Thanks fixed in Aug14
