### ISSUE TITLE
Chapter 5.2 - Notes section introduces int and floats without detail

### ISSUE THREAD

**Issue by davebrochu** [mattharrison/IllustratedPy3#33]
If the intended audience of this is someone new to programming, I'm not the 5.2 note section should  talk about int and float conversion, as some new programmers might not know what those types are.  Or maybe wording at the end about further discussion on types would be helpful so the audience knows not to worry too much about int and float if they aren't familiar

**Comment by mattharrison** [comment]
Thanks for the issue, I've added a note as you suggested in Aug 14 version
