### ISSUE TITLE
4.2 Tip Indentation

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#34]
**The indentation of the 4.2 Tip is confusing to read:**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Using hardcoded hashbangs such as: 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• #!/bin/python3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• #!/usr/bin/python3.3 

Might work fine on your machine, but could lead to problems when you try to share your code and others do not have python3 where you specified it. If you require a specific version of Python, it is common to specify that in the README file.

**It would be clearer to either indent the whole thing, like this:** 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Using hardcoded hashbangs such as: 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; • #!/bin/python3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; • #!/usr/bin/python3.3 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...might work fine on your machine, but could lead to problems when you try to share your code and
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;others do not have python3 where you specified it. If you require a specific version of Python, it is
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;common to specify that in the README file.

**...or you could drop the indentation before and after the bullets like this:**

Using hardcoded hashbangs such as: 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• #!/bin/python3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• #!/usr/bin/python3.3 

...might work fine on your machine, but could lead to problems when you try to share your code and others do not have python3 where you specified it. If you require a specific version of Python, it is common to specify that in the README file.

**Either way, I would drop the capital "M" on "Might" (and instead use "...might") since this is a continuation of the sentence above the bullets.**

Hopefully all that spacing comes through okay--it's hard to indent paragraphs in markdown.

Also, as someone else said, let me know if this is too pedantic and I'll stop. :)

**Comment by mattharrison** [comment]
Agree on the capitalization. LaTeX is formatting this as you read it, which I think is a little confusing, yet correct. It doesn't indent the first paragraph in a note. The "Using hardcoded..." paragraph is then indented and continues with the "might work..." as part of that paragraph, hence the lack of indentation there. Maybe I should just inline the two paths.

(I appreciate how pedantic you are :)) Thanks!

**Comment by mattharrison** [comment]
Aug 29
