### ISSUE TITLE
Chapter 3 - error by running python3 -m idlelib.idle

### ISSUE THREAD

**Issue by mazulo** [mattharrison/IllustratedPy3#35]
When I tried to run the command I got this error:

```shell
$ python3 -m idlelib.idle
** IDLE can't import Tkinter.
Your Python may not be configured for Tk. **
```

To solve this problem it depends on the OS you're using. Btw you have to install the `tk` package on the OS level.

On Ubuntu run:
```shell
$ sudo apt-get install tk-dev
```

On Arch-based run:
```shell
$ sudo pacman -S tk
```

On this [link](https://stackoverflow.com/questions/5459444/tkinter-python-may-not-be-configured-for-tk) you'll can see other ways to do that.

I think that worth to include a note about it.

**Comment by mattharrison** [comment]
Noted in Aug 14. Thanks for the suggestion
