### ISSUE TITLE
7.3 comment notation in REPL examples

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#36]
This is picky, but I don't think you should use comment notation in the examples in 7.3.  First, you haven't noted how to leave comments, so beginners might not realize you are just adding pythonic annotations to the output.  Second, anyone trying this won't see hashtags and exclamations of DIFFERENT! or SAME!.  I'd recommend following each example with a short sentence like "Notice that the id of the variable has changed."  and "Here the id of name stayed exactly the same."  

Another teachable moment you might want to snag is to print(names) in the second example to show that 'Fred' was added to the list.

**Comment by mattharrison** [comment]
Great suggestion. Aug 14
