### ISSUE TITLE
Chapter 2 (Grammar, etc.)

### ISSUE THREAD

**Issue by wynand1004** [mattharrison/IllustratedPy3#4]
Python 2, has served - NO COMMA

The Python Software Foundation, that -> The Python Software Foundation, **which**

This runs Windows, Mac, and Linux -> This runs **on** Windows, Mac, and Linux

Might want to include Visual Studio Code as a good Python text editor.

**Comment by mattharrison** [comment]
Thanks. Fixed in Aug 12
