### ISSUE TITLE
8.8 capitalization

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#40]
Based on the other multiword section headings (such as 8.7 and others), it seems that this section should be "Other operations" with the second word uncapitalized.

**Comment by mattharrison** [comment]
Addressed all heading capitalization in Aug 14 version. Thanks

**Comment by Rad-Prof** [comment]
Could you take another look?  Consider section 9.1 against 9.2 and 9.3.  I don't think Strings should be capitalized since you don't do that in the text.
