### ISSUE TITLE
4.4 Exercises

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#41]
For the sake of preventing copy/paste or transcription errors, would it be worthwhile to drop the period at the end of the last bullet point (of the 4.4 Exercises)? It might prevent readers from attempting to run their script like this:

**If copying/pasting:**
```
$ ./hello
.
```

**If transcribing:**
```
$ ./hello.
```

**Comment by mattharrison** [comment]
Changed formatting to remove trailing . in Aug 15
