### ISSUE TITLE
5.4 Exercises

### ISSUE THREAD

**Issue by mdbaggy** [mattharrison/IllustratedPy3#42]
The exercises would seem to be more complicated to execute than the chapter explains.
How do you get it to print **Hello + name** . I can get it to print hello or the name, Is there an extra bit of code to make this happen?

Maybe more examples would be of use as seeing how strings are put together makes them easier to understand, especially as this is the beginning of the book.

**Comment by mattharrison** [comment]
Check out the Aug 14 version and let me know if the extra examples help

**Comment by mattharrison** [comment]
Aug 29
