### ISSUE TITLE
6.2 "variable" plurality

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#43]
**When variable go away (an example is when we exit a function, variable in that function will go away), the reference count goes down.**

While "variable" is used as a plural noun, you used "variables" in the previous sentence. Either way, I think the usage should stay consistent.

So maybe instead:

When variables go away (an example is when we exit a function, variables in that function will go away), the reference count goes down.

**Comment by mattharrison** [comment]
Great catch. Fixed in Aug14
