### ISSUE TITLE
Numbering the exercises

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#44]
This may be my own personal preference, but I really think the exercises should be numbered.  When it was only one or two, it wasn't bad to say first bullet or second bullet.  There are four exercises in Chapter 8, and now I wish that if I had to reference one I could say Exercise 8.3 or Exercise #3.  Numbering also makes it easier for students who may be learning together to compare notes, or for an instructor to reference an exercise as an assignment unambiguously.  Just imagine if our text editors didn't have line numbers as we were programming or doing code reviews -- yikes!

**Comment by mattharrison** [comment]
Done in Aug 15. Thanks for the great feedback!
