### ISSUE TITLE
9.1 Formatting Strings -- "curly braces with an integer inside it"

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#45]
I'm confused by this explanation.  It seems that "it" refers to string, but the example doesn't have a digit in the string.  Also, if "it" refers to the curly braces, it should be "them", BUT a lot more goes inside the braces (or nothing) than digits as your other examples show.

**Comment by mattharrison** [comment]
Fixed in Aug 15
