### ISSUE TITLE
9.2 Formatting Field-Meaning Tables

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#46]
It will take a few more characters, but I think you should either replace the hyphen which you use to link field options to their meanings with some non-keyboard characters (such as a right-arrow), or just use a few more words.  For example let's look at sign:

sign     + to indicate the sign of all numbers, - to show the sign of only negative numbers, _space_ use for leading space for positive and minus sign for negative

Also, look at parallelism between how you are describing the various fields.  Specifically, grouping_option is readable English, but others don't start with verbs.  

Finally, "grouping_option" needs to be on one line in your table.

**Comment by mattharrison** [comment]
Thanks! Addressed in Aug15
