### ISSUE TITLE
9.3 Percent example 

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#47]
Based on your description "and the sign before the width padding" I think you want to use the + sign flag.  See below:
>>> "Percent: {:=10.1%}".format(44/100)
'Percent:      44.0%'
>>> "Percent: {:=+10.1%}".format(44/100)
'Percent: +    44.0%'
>>> "Percent: {:=+10.1%}".format(-44/100)
'Percent: -    44.0%'

**Comment by mattharrison** [comment]
Fixed in Aug 15
