### ISSUE TITLE
11.8 

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#51]
You may not feel it's worth mentioning here, and perhaps there are better ways to do it, but I often use the .upper() method to normalize user input and then check whether the input starts with or ends with particular characters of interest.  It just seems faster than checking for both 'Q' and 'q'.  Of course .lower() could be used in the same way.  I'm just throwing this out as another useful string method that you might want to mention explicitly rather than lumping in with "Other methods."

**Comment by mattharrison** [comment]
Fixed in Aug15
