### ISSUE TITLE
6.6 Note Tense

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#52]
>Using a built-in name as a variable name shadows the built-in. The new variable name prevents you from getting access to the original built-in. Essentially you took the built-in variable and coopted it for your use. To get access to the original built-in you will need to access it through the \_\_builtins\_\_ module. But it is much better not to shadow it in the first place.

While it's very clear what you mean here, you change tense three times:

**Present:** 
Using a built-in name as a variable name shadows the built-in. The new variable name _prevents you_ from getting access to the original built-in.

**Past:**
Essentially _you took_ the built-in variable and coopted it for your use. 

**Future:**
To get access to the original built-in _you will need_ to access it through the \_\_builtins\_\_ module.

I think it reads better if you maintain the same tense throughout—something like this:

Using a built-in name as a variable name shadows the built-in. The new variable name prevents you from getting access to the original built-in. Doing so essentially takes the built-in variable and coopts it for your use. As a result, access to the original built-in may only be obtained through the \_\_builtins\_\_ module. But it is much better not to shadow it in the first place.

**Comment by mattharrison** [comment]
Awesome! Thanks (Aug 15)
