### ISSUE TITLE
6.2 Inline Variable Formatting

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#53]
>In the above example a was originally pointing to an integer, but then was told to point to a string.

This may simply be another issue with the way my system renders the page, but it was not altogether clear that **a** was referring to the variable name. Context told me so, and after reading it once and thinking at first that I had found an error, I then looked closer and noticed the slight variation in font. But I wonder if it might be beneficial to the reader to distinguish this more?

**Comment by mattharrison** [comment]
Updated code and image to refer to ``a`` as ``num``
