### ISSUE TITLE
Chapter 4: File Navigation Notes Style Suggestion

### ISSUE THREAD

**Issue by EmadMokhtar** [mattharrison/IllustratedPy3#54]
I have a suggestion for this note:
To save space and increase its readability, make the OS as bold text without changing its indentation so you'll have space for your text and it'll fix an issue like in the image below.
![screenshot 2017-07-09 14 02 05](https://user-images.githubusercontent.com/311636/29364528-7379e1b0-829c-11e7-9fd4-3b063d34130a.png)

**Comment by mattharrison** [comment]
Added Appendix with navigation notes
