### ISSUE TITLE
3.2 A REPL example

### ISSUE THREAD

**Issue by vahtras** [mattharrison/IllustratedPy3#57]
I believe that regarding the Note on page 13, taking about the 'sys module' and 'import' is premature and probably confusing for novices, as this actually comes before the first 'hello world'.  As nobody ever changes these prompts I don't think it is necessary at this stage to tell how and where they are defined.

Also the exercises 3.4 on the same topic. A novice might ask, what do you mean by 'running' "hello world"?
Running programs is probably a well-known concept, but so far we do not have programs, we only have a string..., maybe it should just say 'printing'?

**Comment by mattharrison** [comment]
Updated in Aug 15. Added a note about import (and ignoring them). Also expanded a little on the exercises.
