### ISSUE TITLE
7.3 "TODO" looks like stale text

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#59]
End of section 7.4 there is a "TODO" string. Looks like stale string. May be you would like to get rid of it.
Please see below screen shot

![7 4_text](https://user-images.githubusercontent.com/15726294/29382462-9c29cfb4-829a-11e7-95dc-eb597bfd10aa.PNG)

**Comment by mattharrison** [comment]
Actually I intend to add more content here... hence the TODO

**Comment by jaypsingh** [comment]
Ah !! I thought so. Sorry for the confusion.

**Comment by mattharrison** [comment]
Aug 29 fix

**Comment by mattharrison** [comment]
Aug 29 fix
