### ISSUE TITLE
8.6 "Power" can be called as "Exponent"

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#60]
This is more like a suggestion than issue.
Section 8.6 header is "Power". My suggestion is if you can call it "Exponent", since that is a more widely used term.

**Comment by mattharrison** [comment]
Going to leave this as power. But added some more details about base and exponent

http://mathforum.org/library/drmath/view/64570.html

https://docs.python.org/2.0/ref/power.html
