### ISSUE TITLE
Ch 13: comparison operators

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#66]
This could be a stylistic or discipline variation, but in mathematics all the "Check" items in the first table are called "comparison operators" except the last two which are part of python.  So from my perspective (and to build connections to mathematicians and statisticians who may be reading your book or working with people who do), I'd introduce the table as:  "Here is a table of _**comparison**_ operations that **_result in_** boolean values:" and I'd probably change "Check" to "Operator".  

Just something to consider.

**Comment by Rad-Prof** [comment]
Also, this terminology of "comparison operation" or "comparison operator" explains why you didn't include **_in_** in your table because that tests membership.

**Comment by mattharrison** [comment]
Good points. Thanks. Fixed in Aug 15
