### ISSUE TITLE
14.6 wording in last note

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#71]
In the first bullet, I _think_ you mean **consecutive** rather than **subsequent**.

Also I don't think the last line (that starts with "Luckily") should be indented.  I think it is still part of the prior paragraph which includes the quote by Dijkstra.  (Not saying that I agree with his position since I have used a lot of MATLAB in my day, but I'm trying not to take sides in the holy war.)

**Comment by mattharrison** [comment]
Thanks. Sorry about the MATLAB jab. Fixed in Aug 15
