### ISSUE TITLE
14.7 line break on a contraction

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#72]
In the Note on page 95 (105 in the pdf numbering), the contraction "Here's" is split between lines.  Not sure how this is possible, but suggest replacing with "Here is" to avoid this.

**Comment by mattharrison** [comment]
Fixed in Aug 15

**Comment by jaypsingh** [comment]
Also below in the same note you say:
![image](https://user-images.githubusercontent.com/15726294/29548136-72a946ca-86cc-11e7-9138-01c288a27552.png)

Did you mean "_commas_" instead of "_comma's_"
