### ISSUE TITLE
7.1 Identity

### ISSUE THREAD

**Issue by mclaughlin** [mattharrison/IllustratedPy3#75]
>Identity at its lowest level refers to the location in the computer’s memory of an object. 

Grammatically, the _direct object_ of this sentence is the "object's location" and the _indirect object_ is the "computer's memory."  So in this case, you have the indirect object inside the direct object (sorry this sounds confusing given we're talking about objects both in grammar and python).

[direct object] - [indirect object] - [direct object] 
[the location] - [the computers memory] - [of an object]

I think it's stronger to keep them separate, like this:

**Identity at its lowest level refers to an object's location in the computer’s memory.**

>Python has a built-in function—id that tells you the identity of an object.

These two sentences—"Python has a built-in function" and "id tells you the identity of an object"—read much stronger as one. Something like this:

**Python's built-in function called id tells you the identity of an object.**

And together:

**Identity at its lowest level refers to an object's location in the computer’s memory. Python's built-in function called id tells you the identity of an object.**

>This tells Python to give the first variable the same id of name.

"of" should be "as":

**This tells Python to give the first variable the same id as name.**

>The is operator, which checks for identity equality, will validate that they are actually the same: 

It's clearer and stronger to use a restrictive clause rather than non-restrictive:

**The is operator checks for identity equality and validates whether or not the variables point to the same object.**

>If you print either first or name at the REPL, it will print the same value because they are both pointing to the exact same value:

Did you mean "object" (at the end) and not "value":

**If you print either first or name at the REPL, it will print the same value because they are both pointing to the exact same object.**

**Comment by mattharrison** [comment]
Thanks so much! Fixed Aug 15
