### ISSUE TITLE
16.7 keys of mixed types

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#83]
I don't know if you want to note the caveat or add a footnote, but you can have dictionary keys that are of mixed type.  In this case your example showing the built-in function sorted won't work:
>>> temp = {}
>>> temp[2] = 17
>>> temp['three'] = 0
>>> temp['four'] = -3
>>> temp
{2: 17, 'three': 0, 'four': -3}
>>> for key in sorted(temp.keys()): print(key)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: str() < int()

**Comment by mattharrison** [comment]
I added a note about not mixing types in dictionary keys. Aug 15
