### ISSUE TITLE
13.1 Can be reworded (Suggestion)

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#86]
Suggestion:

Section 13..1 
![image](https://user-images.githubusercontent.com/15726294/29547038-d6bfb2cc-86c5-11e7-99bf-904d9e2827b7.png)

Can be reworded as below by removing 'the' and ',' after or:
Conditional expressions are combined using boolean logic. This logic consists of _and_, _or_ and _not_ operators.

**Comment by mattharrison** [comment]
Aug 29
