### ISSUE TITLE
14.1 List are used to hold a list of objects

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#88]
In Chapter 14, Section 14.1, where you are introducing list, will it be worth mentioning "List are used to hold a list of objects _of same or different class_".
You have explained well. This is just a suggestion if you feel it helps. 

I had this input because i know often a beginner will have this question in mind and can start comparing list with arrays (if he/she comes for a different language background.)

**Comment by mattharrison** [comment]
Added a note. Aug 15 Typically lists only have a single type in them (even if they support mixing types). If you are mixing types, that is code smell that a tuple is probably what you should be using
