### ISSUE TITLE
14.7 Says Tuples are like "ordered record".

### ISSUE THREAD

**Issue by jaypsingh** [mattharrison/IllustratedPy3#89]
With refrence to below description of tuple:
![image](https://user-images.githubusercontent.com/15726294/29548009-ac35ec6e-86cb-11e7-8743-032ae3bea796.png)

I was wondering if 'ordered' is really a property of tuple ? 
I am pretty sure we can create un-ordered tuple.
I think you meant some thing else here when you said 'you should think tuples as ordered record'.

**Comment by mattharrison** [comment]
Nope, I meant what I wrote. Perhaps you are thinking of a set. A tuple is most definitely ordered.
