### ISSUE TITLE
17.6 missing word

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#93]
I think it would be clearer for the last line to say:  "... when the function **_name_** is passed into the help function."

**Comment by mattharrison** [comment]
It is actually the function object (or the variable pointing to it), not the string name. Any ideas on how to make this clear?

**Comment by Rad-Prof** [comment]
Perhaps adding a sentence to clarify those who share my misperception:

"You might see the syntax as passing the function name, but remember that python is based on objects so it is actually the function object (or the variable pointing to it) that is passed, not the string name."

**Comment by mattharrison** [comment]
Fixed Aug 22
