### ISSUE TITLE
3.2 A REPL Example

### ISSUE THREAD

**Issue by gm3dmo** [mattharrison/IllustratedPy3#98]
This is a tiny tiny problem

"You will see >>>".
![image](https://user-images.githubusercontent.com/4660778/29550686-f21ea0aa-8706-11e7-9c27-27c8689b49a4.png)

However that's not quite true (on my Mac at least) I don't see the 3 chevrons:

![image](https://user-images.githubusercontent.com/4660778/29550674-d8abb950-8706-11e7-824d-080767e9cb6c.png)

Until I have pressed Return:

![image](https://user-images.githubusercontent.com/4660778/29550719-21c2392a-8707-11e7-97a9-a7a8729287f1.png)

only then do they appear.

**Comment by mattharrison** [comment]
You actually do see them, there is just the (blue) warning after.

**Comment by mattharrison** [comment]
Aug 29
